// web/admin/src/components/form/Textarea.vue
<template>
  <div class="textarea">
    <label :for="id" :class="error ? '!border-red-500' : ''">
      <Field as="textarea" v-model="model" :rules="rules" :id="id" :name="id" class="form-textarea text peer" :rows="rows" placeholder="Enter any additional order notes...">
        {{ $slots.default ? $slots.default()[0].children : "" }}
      </Field>
      <span class="title">{{ name }}</span>
    </label>
    <span class="text-sm text-red-500 pl-4" v-if="error">{{ error }}</span>
  </div>
</template>

<script setup>
import { computed } from "vue";
import { Field } from 'vee-validate'

const props = defineProps({
  modelValue: {
    required: true,
  },
  id: {
    type: String,
    default: "name",
  },
  name: {
    type: String,
    default: "Name",
  },
  color: {
    type: String,
    default: "indigo",
  },
  rows: {
    type: Number,
    default: 4,
  },
  rules: String,
  error: String,
});

const emits = defineEmits(["update:modelValue"]);

const model = computed({
  get: () => {
    return props.modelValue;
  },
  set: (val) => {
    emits("update:modelValue", val);
  },
});
</script>

<style lang="scss" scoped>
.textarea {
  & label {
    @apply relative block rounded border border-gray-200 text-sm shadow-sm focus-within:border-blue-600 focus-within:ring-1 focus-within:ring-blue-600 p-0;
    
    & .text {
      @apply w-full resize-none border-none bg-transparent placeholder-transparent focus:border-transparent focus:outline-none focus:ring-0;
    }

    .title {
      @apply pointer-events-none absolute start-2.5 top-0 -translate-y-1/2 bg-zinc-50 p-0.5 text-xs text-gray-700 peer-focus:top-0 peer-focus:text-xs;
    }
  }
}
</style>

// web/admin/src/lib/components/form/Textarea.svelte
<script lang="ts">
  import SvgIcon from '../SvgIcon.svelte';

  export let id: string = 'name';
  export let title: string = 'Name';
  export let ico: string | undefined = undefined;
  export let error: string | undefined = undefined;
  export let value: string = '';
  export let placeholder: string = '';
  export let rows: number = 4;

  $: computedPlaceholder = placeholder || `Enter ${id}`;
</script>

<div>
  <label for={id} class={error ? 'border-red-500' : ''}>
    <textarea
      {id}
      bind:value
      {rows}
      class="form-textarea field peer"
      placeholder={computedPlaceholder}
      on:focusout
    ></textarea>
    {#if title}
      <span class="peer-placeholder-shown:top-1/2 peer-placeholder-shown:text-sm peer-focus:top-0 peer-focus:text-xs peer-placeholder-shown:text-gray-400 peer-focus:text-gray-700 title">
        {title}
      </span>
    {/if}
    {#if ico}
      <span class="ico">
        <SvgIcon name={ico} stroke="currentColor" className="h-5 w-5 {error ? 'text-red-500' : 'text-gray-400'}" />
      </span>
    {/if}
  </label>
  {#if error}
    <span class="error">{error}</span>
  {/if}
</div>
