// web/admin/src/lib/components/Drawer.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { createEventDispatcher } from 'svelte';

  export let isOpen: boolean = false;
  export let maxWidth: string = "500px";
  export let backgroundColor: string = "#fafafa";

  const dispatch = createEventDispatcher();
  let isVisible = false;
  let isTransitioning = false;
  let drawerContent: HTMLElement;

  $: if (isOpen) {
    if (drawerContent) {
      drawerContent.scrollTop = 0;
    }
    toggleBackgroundScrolling(true);
    isVisible = true;
    // Force reflow for animation
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        // Animation will trigger via class binding
      });
    });
  } else {
    toggleBackgroundScrolling(false);
    setTimeout(() => {
      isVisible = false;
    }, 200);
  }

  function toggleBackgroundScrolling(enable: boolean) {
    const body = document.querySelector("body");
    if (body) {
      body.style.overflow = enable ? "hidden" : "";
    }
  }

  function closeDrawer(event: MouseEvent) {
    if (!isTransitioning && event.target === event.currentTarget) {
      isTransitioning = true;
      setTimeout(() => {
      dispatch('close');
        isTransitioning = false;
      }, 200);
    }
  }

  function handleClickOutside(event: MouseEvent) {
    // Only close if clicking on the overlay, not on drawer content
    const target = event.target as HTMLElement;
    if (drawerContent && target) {
      // Check if click was on the overlay (has overlay class)
      const overlay = target.closest('.overlay');
      if (overlay && !drawerContent.contains(target)) {
      if (!isTransitioning) {
          isTransitioning = true;
          setTimeout(() => {
        dispatch('close');
            isTransitioning = false;
          }, 200);
        }
      }
    }
  }
  
  function handleClose() {
    if (!isTransitioning) {
      isTransitioning = true;
      // Don't modify isOpen directly, let parent handle it
      setTimeout(() => {
        dispatch('close');
        isTransitioning = false;
      }, 200);
    }
  }

  onMount(() => {
    // Remove handleClickOutside as we use closeDrawer on overlay directly
    // document.addEventListener('click', handleClickOutside);
  });

  onDestroy(() => {
    // document.removeEventListener('click', handleClickOutside);
    toggleBackgroundScrolling(false);
  });
</script>

{#if isVisible}
  <div class="drawer">
    <div
      class="overlay fixed inset-x-0 inset-y-0 z-50 w-full select-none bg-black transition-opacity {isOpen ? 'opacity-50' : 'opacity-0'}"
      style="transition-duration: 200ms"
      role="button"
      tabindex="0"
      aria-label="Close drawer"
      on:click={closeDrawer}
      on:keydown={(e) => {
        if (e.key === 'Escape' || e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          closeDrawer(e);
        }
      }}
    ></div>

    <div
      bind:this={drawerContent}
      id="drawer_content"
      class="content {isOpen ? 'translate-x-0' : 'translate-x-full'}"
      style="max-width: {maxWidth}; transition-duration: 200ms; background-color: {backgroundColor};"
    >
      <slot />
    </div>
  </div>
{/if}

<style>
  @reference "tailwindcss";
  
  :global(.drawer .content) {
    @apply fixed inset-y-0 right-0 z-[999] flex h-full w-full flex-col overflow-auto bg-white p-6 shadow-2xl transition-transform;
  }
</style>

// web/admin/src/components/Drawer.vue
<template>
  <div :class="isVisible ? 'visible' : 'invisible'" class="drawer">
    <div class="fixed inset-x-0 inset-y-0 z-50 w-full select-none bg-black opacity-0 transition-opacity" style="transitionduration: `200 ms`" :class="{ 'opacity-50': isOpen }"></div>

    <div id="drawer_content" class="content" v-click-outside="closeDrawer" :class="isOpen ? 'translate-x-0' : 'translate-x-full'" :style="{
      maxWidth: maxWidth,
      transitionDuration: `200 ms`,
      backgroundColor: backgroundColor,
    }">
      <slot />
    </div>
  </div>
</template>

<script setup>
import { getCurrentInstance, watch, ref } from "vue";

const { emit } = getCurrentInstance();
const isVisible = ref(false);
const isTransitioning = ref(false);
const props = defineProps({
  title: {
    type: String,
    default: "Header",
  },
  isOpen: {
    type: Boolean,
    required: false,
    default: false,
  },
  maxWidth: {
    type: String,
    required: false,
    default: "500px",
  },
  backgroundColor: {
    type: String,
    required: false,
    default: "#fafafa",
  },
});

watch(
  () => props.isOpen,
  (val) => {
    isTransitioning.value = true;

    if (val) {
      const drawerContent = document.getElementById("drawer_content");
      drawerContent.scrollTop = 0;
      toggleBackgroundScrolling(true);
      isVisible.value = true;
    } else {
      toggleBackgroundScrolling(false);
      setTimeout(() => (isVisible.value = false), 200);
    }
    setTimeout(() => (isTransitioning.value = false), 200);
  },
);

const toggleBackgroundScrolling = (enable) => {
  const body = document.querySelector("body");
  body.style.overflow = enable ? "hidden" : null;
};

const closeDrawer = () => {
  if (!isTransitioning.value) {
    emit("close");
  }
};

const vClickOutside = {
  mounted: (el, binding) => {
    el.clickOutsideEvent = function (event) {
      if (!(el == event.target || el.contains(event.target))) {
        binding.value(event, el);
      }
    };
    document.addEventListener("click", el.clickOutsideEvent);
  },
  unmounted: (el, binding) => {
    document.removeEventListener("click", el.clickOutsideEvent);
  },
};
</script>

<style scoped>
@reference "../assets/app.css";

.drawer .content {
  @apply fixed inset-y-0 right-0 z-[999] flex h-full w-full flex-col overflow-auto bg-red-200 p-6 shadow-2xl transition-transform;
}
</style>
