// web/admin/src/lib/components/product/Digital.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createEventDispatcher } from 'svelte';
  import FormInput from '../form/Input.svelte';
  import FormButton from '../form/Button.svelte';
  import Upload from '../form/Upload.svelte';
  import SvgIcon from '../SvgIcon.svelte';
  import { loadData } from '$lib/utils/apiHelpers';
  import { apiPost, apiUpdate, apiDelete } from '$lib/utils/api';
  import { showMessage } from '$lib/utils';
  import type { Product } from '$lib/types/models';

  interface Digital {
    type: string;
    files: Array<{
      id: string;
      name: string;
      ext: string;
      orig_name?: string;
    }>;
    data: Array<{
      id: string;
      content: string;
      cart_id: string | null;
    }>;
  }

  interface DrawerProduct {
    product: Product;
    index: number;
    currency?: string;
  }

  export let drawer: DrawerProduct;
  export let onContentUpdate: (() => void) | undefined = undefined;

  const dispatch = createEventDispatcher();

  let digital: Digital = {
    type: '',
    files: [],
    data: []
  };
  let loading = true;

  onMount(async () => {
    await loadDigital();
  });

  async function loadDigital() {
    loading = true;
    const result = await loadData<Digital>(`/api/_/products/${drawer.product.id}/digital`, 'Failed to load digital content');
    if (result) {
      digital = {
        type: result.type || '',
        files: result.files || [],
        data: result.data || []
      };
    }
    loading = false;
  }

  function close() {
    dispatch('close');
  }

  async function handleUpload(event: CustomEvent) {
    if (event.detail.success && event.detail.result) {
      digital.files = [...digital.files, event.detail.result];
      showMessage('File uploaded', 'connextSuccess');
      if (onContentUpdate) {
        onContentUpdate();
      }
    }
  }

  async function addDigitalData() {
    const result = await apiPost(`/api/_/products/${drawer.product.id}/digital`);
    if (result.success && result.result) {
      digital.data = [...digital.data, result.result];
      showMessage('Data added', 'connextSuccess');
      if (onContentUpdate) {
        onContentUpdate();
      }
    } else {
      showMessage(result.message || 'Failed to add data', 'connextError');
    }
  }

  async function saveData(index: number) {
    const dataItem = digital.data[index];
    if (!dataItem || dataItem.cart_id !== null) return;

    const update = {
      content: dataItem.content
    };
    const result = await apiUpdate(`/api/_/products/${drawer.product.id}/digital/${dataItem.id}`, update);
    if (result.success) {
      showMessage('Data saved', 'connextSuccess');
    } else {
      showMessage(result.message || 'Failed to save data', 'connextError');
    }
  }

  async function deleteDigital(type: 'file' | 'data', index: number) {
    const digitalId = type === 'file' ? digital.files[index].id : digital.data[index].id;
    const result = await apiDelete(`/api/_/products/${drawer.product.id}/digital/${digitalId}`);
    
    if (result.success) {
      if (type === 'file') {
        digital.files = digital.files.filter((_, i) => i !== index);
      } else {
        digital.data = digital.data.filter((_, i) => i !== index);
      }
      showMessage('Deleted', 'connextSuccess');
      if (onContentUpdate) {
        onContentUpdate();
      }
    } else {
      showMessage(result.message || 'Failed to delete', 'connextError');
    }
  }
</script>

<div>
  <div class="pb-8">
    <div class="flex items-center">
      <div class="pr-3">
        <h1>Digital {digital.type}</h1>
        {#if digital.type === 'file'}
          <p class="mt-4">This is the product that the user purchases. Upload the files that will be sent to the buyer after payment to the email address provided during checkout.</p>
        {/if}
        {#if digital.type === 'data'}
          <p class="mt-4">Enter the digital product that you intend to sell. It can be a unique item, such as a license key.</p>
        {/if}
      </div>
    </div>
  </div>

  {#if loading}
    <div class="text-center py-8">Loading...</div>
  {:else if digital.type === 'file'}
    <!-- File section -->
    <div class="flow-root">
      <div class="-my-3 mx-auto mb-0 mt-2 space-y-4 text-sm">
        {#if digital.files && digital.files.length > 0}
          <div class="grid content-start">
            {#each digital.files as file, index}
              <div class="relative mt-4 flex first:mt-0">
                <a href="/secrets/{file.name}.{file.ext}" target="_blank" class="rounded-lg bg-gray-200 px-3 py-3" rel="noopener noreferrer">
                  {file.orig_name || file.name}.{file.ext}
                </a>
                <div 
                  class="ml-3 mt-3 cursor-pointer" 
                  role="button" 
                  tabindex="0"
                  on:click={() => deleteDigital('file', index)}
                  on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); deleteDigital('file', index); } }}
                >
                  <SvgIcon name="trash" className="h-5 w-5" stroke="currentColor" />
                </div>
              </div>
            {/each}
          </div>
        {/if}
        <Upload
          section="digital"
          productId={drawer.product.id}
          on:added={handleUpload}
        />
      </div>
    </div>
  {:else if digital.type === 'data'}
    <!-- Data section -->
    <div class="flow-root">
      <div class="-my-3 mx-auto mb-0 mt-4 space-y-4 text-sm">
        {#if digital.data && digital.data.length > 0}
          {#each digital.data as dataItem, index}
            <div class="flex">
              {#if dataItem.cart_id === null || dataItem.cart_id === ''}
                <div class="grow">
                  <FormInput
                    id="data-{dataItem.id}"
                    type="text"
                    title=""
                    bind:value={dataItem.content}
                    on:blur={() => saveData(index)}
                  />
                </div>
                <div 
                  class="flex-none cursor-pointer pl-3 pt-3" 
                  role="button" 
                  tabindex="0"
                  on:click={() => deleteDigital('data', index)}
                  on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); deleteDigital('data', index); } }}
                >
                  <SvgIcon name="trash" className="h-5 w-5" stroke="currentColor" />
                </div>
              {:else}
                <div class="grow">
                  <div class="rounded-lg bg-gray-200 px-3 py-3">
                    {dataItem.content}
                  </div>
                </div>
              {/if}
            </div>
          {/each}
        {/if}
        <div class="flex">
          <div class="grow"></div>
          <div class="mt-2 flex-none">
            <button 
              type="button" 
              class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" 
              on:click={addDigitalData}
            >
              Add data
            </button>
          </div>
        </div>
      </div>
    </div>
  {:else}
    <div class="mt-4 flow-root">Select digital type</div>
  {/if}

  <div class="pt-5">
    <FormButton type="button" name="Close" color="green" on:click={close} />
  </div>
</div>

// web/admin/src/components/product/Digital.vue
<template>
  <div>
    <div class="pb-8">
      <div class="flex items-center">
        <div class="pr-3">
          <h1>Digital {{ digital.type }}</h1>
          <p class="mt-4" v-if="digital.type === 'file'">This is the product that the user purchases. Upload the files that will be sent to the buyer after payment to the email address provided during checkout.</p>
          <p class="mt-4" v-if="digital.type === 'data'">Enter the digital product that you intend to sell. It can be a unique item, such as a license key.</p>
        </div>
      </div>
    </div>

    <!-- File section -->
    <div class="flow-root" v-if="digital.type === 'file'">
      <div class="-my-3 mx-auto mb-0 mt-2 space-y-4 text-sm">
        <div class="grid content-start" v-if="digital.files !== null">
          <div v-for="(value, index) in digital.files" class="relative mt-4 flex first:mt-0">
            <a :href="`/secrets/${value.name}.${value.ext}`" target="_blank" class="rounded-lg bg-gray-200 px-3 py-3">
              {{ value.name }}.{{ value.ext }}
            </a>
            <SvgIcon name="trash" stroke="currentColor" class="ml-3 mt-3 h-5 w-5 cursor-pointer" @click="deleteDigital('file', index)" />
          </div>
        </div>
        <FormUpload :productId="`${drawer.product.id}`" section="digital" @added="addDigitalFile" />
      </div>
    </div>

    <!-- Data section -->
    <div class="flow-root" v-if="digital.type === 'data'">
      <div class="-my-3 mx-auto mb-0 mt-4 space-y-4 text-sm">
        <div class="flex" v-for="(value, index) in digital.data" :key="index">
          <div class="grow" v-if="digital.data[index].cart_id === ''">
            <FormInput v-model="digital.data[index].content" :id="`${digital.data[index].id}`" type="text" title="" @focusout="saveData(index)" />
          </div>
          <div class="grow" v-else>
            <div class="rounded-lg bg-gray-200 px-3 py-3">
              {{ digital.data[index].content }}
            </div>
          </div>
          <div class="flex-none cursor-pointer pl-3 pt-3" @click="deleteDigital('data', index)" v-if="digital.data[index].cart_id === ''">
            <SvgIcon name="trash" stroke="currentColor" class="h-5 w-5" />
          </div>
        </div>
        <div class="flex">
          <div class="grow"></div>
          <div class="mt-2 flex-none">
            <a href="#" class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" @click="addDigitalData">
              Add data
            </a>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-4 flow-root" v-if="!digital.type">Select digital type</div>
  </div>
</template>

<script setup>
import { onMounted, ref } from "vue";

import FormInput from "@/components/form/Input.vue";
import FormUpload from "@/components/form/Upload.vue";
import { showMessage } from "@/utils/message";
import { apiGet, apiPost, apiUpdate, apiDelete } from "@/utils/api";

const props = defineProps({
  drawer: {
    required: true,
  },
  close: Function,
});

const digital = ref({});

onMounted(() => {
  listDigitals();
});

const listDigitals = async () => {
  apiGet(`/api/_/products/${props.drawer.product.id}/digital`).then(res => {
    if (res.success && res.result !== null) {
      digital.value.type = res.result.type;
      digital.value.files = res.result.files ?? [];
      digital.value.data = res.result.data ?? [];
    }
  });
};

const addDigitalFile = (e) => {
  if (e.success) {
    digital.value.files.push(e.result);
  }
};

const deleteDigital = async (type, index) => {
  var digitalId;
  switch (type) {
    case "file":
    digitalId = digital.value.files[index].id;
      break;
    case "data":
    digitalId = digital.value.data[index].id;
      break;
  }

  apiDelete(`/api/_/products/${props.drawer.product.id}/digital/${digitalId}`).then(res => {
    if (res.success) {
      switch (type) {
        case "file":
          digital.value.files.splice(index, 1);
          break;
        case "data":
          digital.value.data.splice(index, 1);
          break;
      }
    } else {
      showMessage(res.result, "connextError");
    }
  });
};

const addDigitalData = async () => {
  apiPost(`/api/_/products/${props.drawer.product.id}/digital`).then(res => {
    if (res.success) {

      digital.value.data.push(res.result);
    } else {
      showMessage(res.result, "connextError");
    }
  });
};

const saveData = async (index) => {
  const update = {
    content: digital.value.data[index].content,
  };
  apiUpdate(`/api/_/products/${props.drawer.product.id}/digital/${digital.value.data[index].id}`, update)
};
</script>
