// web/admin/src/lib/components/product/View.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createEventDispatcher } from 'svelte';
  import FormButton from '../form/Button.svelte';
  import DetailList from '../DetailList.svelte';
  import SvgIcon from '../SvgIcon.svelte';
  import { costFormat, formatDate } from '$lib/utils';
  import { loadData } from '$lib/utils/apiHelpers';
  import type { Product } from '$lib/types/models';

  interface DrawerProduct {
    product: Product;
    index: number;
    currency?: string;
  }

  export let drawer: DrawerProduct;
  export let updateActive: ((index: number) => void) | undefined;

  let product: Product | null = null;

  const dispatch = createEventDispatcher();

  onMount(async () => {
    const result = await loadData<Product>(`/api/_/products/${drawer.product.id}`, 'Failed to load product');
    if (result) {
      product = result;
    }
  });

  function close() {
    dispatch('close');
  }

  async function active() {
    if (updateActive && product) {
      await updateActive(drawer.product.index);
      // Update local product state reactively
      if (product) {
        product = { ...product, active: !product.active };
      }
    }
  }
</script>

<div>
  <div class="pb-8">
    <div class="flex items-center">
      <div class="pr-3">
        <h1>View {product?.name || 'Product'}</h1>
      </div>
      <div>
        {#if product}
          <SvgIcon name={product.active ? 'eye' : 'eye-slash'} className="h-5 w-5 cursor-pointer" on:click={active} stroke="currentColor" />
        {/if}
      </div>
    </div>
  </div>

  {#if product}
  <div class="flow-root">
    <dl class="-my-3 mt-2 divide-y divide-gray-100 text-sm">
      <DetailList name="ID">{product.id}</DetailList>
      <DetailList name="Name">{product.name}</DetailList>
        <DetailList name="Price">{costFormat(product.amount)} {drawer.currency || ''}</DetailList>
      <DetailList name="Slug">{product.slug}</DetailList>
      <DetailList name="Metadata">
        {#each product.metadata || [] as data}
          <div>{data.key}: {data.value}</div>
        {/each}
      </DetailList>
      <DetailList name="Attributes">
        {#each product.attributes || [] as item}
          <div>{item}</div>
        {/each}
      </DetailList>
      <DetailList name="Created">{formatDate(product.created)}</DetailList>
      {#if product.updated}
        <DetailList name="Updated">{formatDate(product.updated)}</DetailList>
      {/if}
      {#if product.images}
        <DetailList name="Images" grid={true}>
          {#each product.images as item}
            <div>
                <a href="/uploads/{item.name}.{item.ext}" target="_blank" aria-label="View full size image">
                  <img style="width: 100%; max-width: 150px" src="/uploads/{item.name}_sm.{item.ext}" alt="{product.name} - {item.name}" loading="lazy" />
              </a>
            </div>
          {/each}
        </DetailList>
      {/if}
      <DetailList name="Brief (short description)">{product.brief}</DetailList>

        <div class="pt-3 tiptap" innerHTML={product.description || ''}></div>
    </dl>
  </div>
  {:else}
    <div class="text-center py-8">Loading...</div>
  {/if}

  <div class="pt-5">
    <FormButton type="button" name="Close" color="green" on:click={close} />
  </div>
</div>

// web/admin/src/components/product/View.vue
<template>
  <div>
    <div class="pb-8">
      <div class="flex items-center">
        <div class="pr-3">
          <h1>View {{ product.name }}</h1>
        </div>
        <div>
          <SvgIcon :name="product.active ? 'eye' : 'eye-slash'" class="h-5 w-5 cursor-pointer" @click="active" stroke="currentColor" />
        </div>
      </div>
    </div>

    <div class="flow-root">
      <dl class="-my-3 mt-2 divide-y divide-gray-100 text-sm">
        <DetailList name="ID">{{ product.id }}</DetailList>
        <DetailList name="Name">{{ product.name }}</DetailList>
        <DetailList name="Price">{{ costFormat(product.amount) }} {{ drawer.currency }}</DetailList>
        <DetailList name="Slug">{{ product.slug }}</DetailList>
        <DetailList name="Metadata">
          <div v-for="(data, index) in product.metadata">
            {{ data.key }}: {{ data.value }}
          </div>
        </DetailList>
        <DetailList name="Attributes">
          <div v-for="item in product.attributes">{{ item }}</div>
        </DetailList>
        <DetailList name="Created">{{ formatDate(product.created) }}</DetailList>
        <DetailList name="Updated" v-if="product.updated">{{ formatDate(product.updated) }}</DetailList>
        <DetailList name="Images" :grid="true" v-if="product.images">
          <div v-for="item in product.images">
            <a :href="`/uploads/${item.name}.${item.ext}`" target="_blank">
              <img style="width: 100%; max-width: 150px" :src="`/uploads/${item.name}_sm.${item.ext}`" loading="lazy" />
            </a>
          </div>
        </DetailList>

        <DetailList name="Brief (short description)">{{ product.brief }}</DetailList>

        <div v-html="product.description" class="pt-3 tiptap"></div>
      </dl>
    </div>

    <div class="pt-8">
      <FormButton type="submit" name="Close" color="green" @click="close" />
    </div>
  </div>
</template>

<script setup>
import { onMounted, ref } from "vue";

import FormButton from "@/components/form/Button.vue";
import DetailList from "@/components/DetailList.vue";
import { costFormat, formatDate } from "@/utils/";
import { apiGet } from "@/utils/api";

const props = defineProps({
  drawer: {
    required: true,
  },
  updateActive: Function,
  close: Function,
});

const product = ref({})

onMounted(() => {
  getProduct(props.drawer.product.id)
});

const getProduct = async (id) => {
  apiGet(`/api/_/products/${id}`).then(res => {
    if (res.success) {
      product.value = res.result;
    } else {
      showMessage(res.result, "connextError");
    }
  });
};

const active = async () => {
  props.updateActive(props.drawer.product.index);
  product.value.active = !product.value.active;
};
</script>
