// web/admin/src/components/Badge.vue
<template>
  <span class="badge">
    <SvgIcon :name="ico" stroke="currentColor" :class="ico ? '-ms-0.5 me-1.5 ' + svgClass : 'h-0 w-0'" v-if="ico" />
    <p>
      <slot />
    </p>
  </span>
</template>

<script setup>
const props = defineProps({
  ico: String,
  svgClass: {
    type: String,
    required: false,
    default: "-ms-0.5 me-5.5 h-5 w-5",
  },
});
</script>

<style lang="scss" scoped>
.badge {
  @apply inline-flex items-center justify-center rounded-full px-2.5 py-0.5;

  & p {
    @apply whitespace-nowrap text-xs;
  }
}
</style>

// web/admin/src/lib/components/Badge.svelte
<script lang="ts">
  import SvgIcon from './SvgIcon.svelte';

  export let ico: string | undefined = undefined;
  export let svgClass: string = "-ms-0.5 me-5.5 h-5 w-5";
</script>

<span class="badge">
  {#if ico}
    <SvgIcon name={ico} stroke="currentColor" className={ico ? `-ms-0.5 me-1.5 ${svgClass}` : 'h-0 w-0'} />
  {/if}
  <p>
    <slot />
  </p>
</span>

<style>
  @reference "tailwindcss";
  
  :global(.badge) {
    @apply inline-flex items-center justify-center rounded-full px-2.5 py-0.5;
  }

  :global(.badge p) {
    @apply whitespace-nowrap text-xs;
  }
</style>
