// web/admin/src/pages/settings/webhook.vue
<template>
  <div class="pb-10">
    <header class="mb-4">
      <h1>Webhook events</h1>
    </header>

    <Form @submit="updateSetting" v-slot="{ errors }">
      <FormInput v-model.trim="webhook.url" :error="errors.webhook_url" rules="url" class="max-w-md" id="webhook_url" type="text" title="webhook url" ico="key" />
      <div class="pt-5">
        <FormButton type="submit" name="Save" color="green" />
      </div>
    </Form>
  </div>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { FormInput, FormButton } from "@/components/";
import { showMessage } from "@/utils/message";
import { apiGet, apiUpdate } from "@/utils/api";
import { Form } from "vee-validate";

const webhook = ref({});

onMounted(() => {
  apiGet(`/api/_/settings/webhook`).then(res => {
    if (res.success) {
      webhook.value = res.result;
    }
  });
});

const updateSetting = async () => {
  await apiUpdate(`/api/_/settings/webhook`, webhook.value).then(res => {
    if (res.success) {
      showMessage(res.message);
    } else {
      showMessage(res.result, "connextError");
    }
  });
};
</script>

// web/admin/src/routes/settings/webhook/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import Main from '$lib/layouts/Main.svelte'
  import FormButton from '$lib/components/form/Button.svelte'
  import FormInput from '$lib/components/form/Input.svelte'
  import { loadSettings, saveSettings } from '$lib/utils/settingsHelpers'

  interface WebhookSettings {
    url: string
  }

  let formData: WebhookSettings = {
    url: ''
  }
  let formErrors: Record<string, string> = {}
  let loading = true

  onMount(async () => {
    formData = await loadSettings<WebhookSettings>('webhook', formData)
    loading = false
  })

  async function handleSubmit() {
    formErrors = {}

    if (formData.url && !/^https?:\/\/.+/.test(formData.url)) {
      formErrors.url = 'Valid URL is required (e.g., https://example.com/webhook)'
      return
    }

    await saveSettings('webhook', formData)
  }
</script>

<svelte:component this={Main}>
  <h1 class="mb-5">Webhook Settings</h1>

  {#if loading}
    <div class="py-8 text-center">Loading...</div>
  {:else}
    <form on:submit|preventDefault={handleSubmit} class="max-w-2xl space-y-4">
      <FormInput
        id="url"
        type="url"
        title="Webhook URL"
        bind:value={formData.url}
        error={formErrors.url}
        ico="webhook"
        placeholder="https://example.com/webhook"
      />
      <div class="pt-4">
        <FormButton type="submit" name="Save" color="green" />
      </div>
    </form>
  {/if}
</svelte:component>
