// web/admin/src/routes/carts/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import Main from '$lib/layouts/Main.svelte'
  import SvgIcon from '$lib/components/SvgIcon.svelte'
  import { loadData, handleApiCall } from '$lib/utils/apiHelpers'
  import { apiPost } from '$lib/utils'
  import { costFormat, formatDate } from '$lib/utils'
  import type { Cart } from '$lib/types/models'

  let carts: Cart[] = []
  let loading = true

  onMount(async () => {
    await loadCarts()
  })

  async function loadCarts() {
    loading = true
    const result = await loadData<Cart[]>('/api/_/carts', 'Failed to load carts')
    if (result) {
      carts = result
    }
    loading = false
  }

  async function sendMail(cartId: string) {
    await handleApiCall(
      () => apiPost(`/api/_/carts/${cartId}/mail`, {}),
      'Mail sent successfully',
      'Failed to send mail'
    )
  }
</script>

<svelte:component this={Main}>
  <div class="mb-5 flex items-center justify-between">
    <h1>Carts</h1>
  </div>

  {#if loading}
    <div class="py-8 text-center">Loading...</div>
  {:else if carts.length === 0}
    <div class="py-8 text-center text-gray-500">No carts found</div>
  {:else}
    <table>
      <thead>
        <tr>
          <th>Email</th>
          <th>Price</th>
          <th>Status</th>
          <th>Payment</th>
          <th class="w-48">Created</th>
          <th class="w-48">Updated</th>
          <th class="w-12"></th>
        </tr>
      </thead>
      <tbody>
        {#each carts as cart}
          <tr class:bg-green-50={cart.payment_status === 'paid'}>
            <td>{cart.email || '-'}</td>
            <td>
              {#if cart.payment_id}
                <a href="https://dashboard.stripe.com/payments/{cart.payment_id}" target="_blank">
                  {costFormat(cart.amount_total)}
                  {cart.currency || ''}
                </a>
              {:else}
                {costFormat(cart.amount_total)} {cart.currency || ''}
              {/if}
            </td>
            <td
              class={cart.payment_status === 'paid'
                ? 'text-green-600'
                : cart.payment_status === 'pending'
                  ? 'text-yellow-600'
                  : cart.payment_status === 'failed'
                    ? 'text-red-600'
                    : 'text-gray-600'}
            >
              {cart.payment_status || '-'}
            </td>
            <td>{cart.payment_system || '-'}</td>
            <td>{formatDate(cart.created)}</td>
            <td>
              {#if cart.updated}
                {formatDate(cart.updated)}
              {/if}
            </td>
            <td>
              {#if cart.payment_status === 'paid'}
                <SvgIcon
                  name="envelope"
                  className="h-5 w-5 cursor-pointer"
                  on:click={() => sendMail(cart.id)}
                  stroke="currentColor"
                />
              {:else}
                <SvgIcon name="envelope" className="h-5 w-5 opacity-30" stroke="currentColor" />
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</svelte:component>

// web/admin/src/pages/Carts.vue
<template>
  <MainLayouts>
    <header>
      <h1 class="pb-4">Carts</h1>
    </header>

    <div class="mx-auto pb-16" v-if="carts.length > 0">
      <table>
        <thead>
          <tr>
            <th>Email</th>
            <th>Price</th>
            <th>Status</th>
            <th>Payment</th>
            <th class="w-32">Created</th>
            <th class="w-32">Updated</th>
            <th class="w-12"></th>
          </tr>
        </thead>
        <tbody>
          <tr :class="{ 'bg-green-50': item.payment_status === 'paid' }" v-for="(item, index) in carts">
            <td>{{ item.email }}</td>
            <td>
              <a :href="`https://dashboard.stripe.com/payments/${item.payment_id}`" target="_blank">
                {{ costFormat(item.amount_total) }} {{ item.currency }}
              </a>
            </td>
            <td>{{ item.payment_status }}</td>
            <td>{{ item.payment_system }}</td>
            <td>{{ formatDate(item.created) }}</td>
            <td v-if="item.updated">{{ formatDate(item.updated) }}</td>
            <td v-else></td>
            <td>
              <SvgIcon name="envelope" stroke="currentColor" class="h-5 w-5" v-if="item.payment_status === 'paid'" @click="sendEmail(item.id)" />
              <SvgIcon name="envelope" stroke="currentColor" class="h-5 w-5 opacity-30" v-else />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="mx-auto" v-else>Not found carts</div>
  </MainLayouts>
</template>

<script setup>
import { onMounted, ref } from "vue";
import MainLayouts from "@/layouts/Main.vue";
import { costFormat, formatDate } from "@/utils/";
import { showMessage } from "@/utils/message";
import { apiGet, apiPost } from "@/utils/api";

const carts = ref([]);

onMounted(() => {
  listCarts();
});

const listCarts = async () => {
  apiGet(`/api/_/carts`).then(res => {
    if (res.success) {
      carts.value = res.result;
    }
  })
};

const sendEmail = async (id) => {
  apiPost(`/api/_/carts/${id}/mail`).then(res => {
    if (res.success) {
      showMessage(res.message);
    } else {
      showMessage(res.result, "connextError");
    }
  });
};
</script>
