// web/admin/src/routes/products/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Main from '$lib/layouts/Main.svelte';
  import Drawer from '$lib/components/Drawer.svelte';
  import ProductView from '$lib/components/product/View.svelte';
  import ProductSeo from '$lib/components/product/Seo.svelte';
  import ProductDigital from '$lib/components/product/Digital.svelte';
  import FormButton from '$lib/components/form/Button.svelte';
  import FormInput from '$lib/components/form/Input.svelte';
  import FormSelect from '$lib/components/form/Select.svelte';
  import FormTextarea from '$lib/components/form/Textarea.svelte';
  import Editor from '$lib/components/Editor.svelte';
  import Upload from '$lib/components/form/Upload.svelte';
  import SvgIcon from '$lib/components/SvgIcon.svelte';
  import { loadData, saveData, deleteData, toggleActive as toggleActiveApi } from '$lib/utils/apiHelpers';
  import { costFormat, formatDate, sortByDate, confirmDelete, showMessage } from '$lib/utils';
  import { apiDelete, apiUpdate } from '$lib/utils/api';
  import { validators, validateFields } from '$lib/utils/validation';
  import type { Product } from '$lib/types/models';

  interface ProductsResponse {
    products: Product[];
    currency: string;
  }

  interface DrawerProduct {
    product: Product;
    index: number;
    currency?: string;
  }

  let products: Product[] = [];
  let currency = '';
  let loading = true;
  let drawerOpen = false;
  let drawerMode: 'view' | 'add' | 'edit' | 'seo' | 'digital' = 'view';
  let drawerProduct: DrawerProduct | null = null;
  let drawerIndex = -1;

  interface ProductFormData {
    name: string;
    slug: string;
    brief: string;
    description: string;
    amount: string | number;
    active: boolean;
    metadata: Array<{ key: string; value: string }>;
    attributes: string[];
    digital: {
      type: '' | 'file' | 'data' | 'api';
    };
  }

  let formData: ProductFormData = {
    name: '',
    slug: '',
    brief: '',
    description: '',
    amount: '0',
    active: true,
    metadata: [],
    attributes: [],
    digital: {
      type: ''
    }
  };
  let amountDisplay = '0';
  let formErrors: Record<string, string> = {};
  let productImages: Product['images'] = [];
  let fullProductData: Product | null = null;

  onMount(async () => {
    await loadProducts();
  });

  async function loadProducts() {
    loading = true;
    const result = await loadData<ProductsResponse>('/api/_/products', 'Failed to load products');
    if (result) {
      products = sortByDate(result.products || []);
      currency = result.currency || '';
    }
    loading = false;
  }

  function openView(product: Product, index: number) {
    drawerProduct = { product, index, currency };
    drawerMode = 'view';
    drawerOpen = true;
  }

  async function openAdd() {
    formData = {
      name: '',
      slug: '',
      brief: '',
      description: '',
      amount: '0',
      active: true,
      metadata: [],
      attributes: [],
      digital: {
        type: ''
      }
    };
    amountDisplay = '0';
    productImages = [];
    fullProductData = null;
    formErrors = {};
    drawerMode = 'add';
    drawerOpen = true;
  }

  async function openEdit(product: Product, index: number) {
    drawerProduct = { product, index };
    formErrors = {};
    drawerMode = 'edit';
    
    const result = await loadData<Product>(`/api/_/products/${product.id}`, 'Failed to load product');
    if (result) {
      fullProductData = result;
      formData = {
        name: result.name || '',
        slug: result.slug || '',
        brief: result.brief || '',
        description: result.description || '',
        amount: result.amount || 0,
        active: result.active !== undefined ? result.active : true,
        metadata: result.metadata || [],
        attributes: result.attributes || [],
        digital: result.digital || { type: '' }
      };
      amountDisplay = costFormat(result.amount);
      productImages = result.images || [];
      drawerOpen = true;
    }
  }

  function openSeo(product: Product, index: number) {
    drawerProduct = { product, index, currency };
    drawerMode = 'seo';
    drawerOpen = true;
  }

  function openDigital(product: Product, index: number) {
    drawerProduct = { product, index, currency };
    drawerMode = 'digital';
    drawerOpen = true;
  }

  async function handleDigitalContentUpdate() {
    await loadProducts();
  }

  function closeDrawer() {
    if (drawerOpen) {
      drawerOpen = false;
      setTimeout(() => {
        drawerProduct = null;
        drawerMode = 'view';
      }, 200);
    }
  }

  function updateProductInList(product: Product) {
    const productIndex = products.findIndex(p => p.id === product.id);
    if (productIndex !== -1) {
      products = products.map((p, i) => 
        i === productIndex ? product : p
      );
    }
    if (drawerProduct && drawerProduct.product.id === product.id) {
      drawerProduct.product = product;
    }
    if (fullProductData && fullProductData.id === product.id) {
      fullProductData = product;
      formData.active = product.active;
    }
  }

  async function handleSubmit() {
    formErrors = validateFields(formData, [
      { field: 'name', ...validators.minLength(3, 'Name must be at least 3 characters') },
      { field: 'slug', ...validators.minLength(3, 'Slug must be at least 3 characters') }
    ]);

    const amountNum = parseFloat(amountDisplay);
    if (isNaN(amountNum) || amountNum < 0) {
      formErrors.amount = 'Amount must be a positive number';
    }

    if (drawerMode === 'add' && (!formData.digital?.type || formData.digital.type.trim() === '')) {
      formErrors.digital_type = 'Digital type is required';
    }

    if (Object.keys(formErrors).length > 0) {
      return;
    }

    const isUpdate = drawerMode === 'edit' && drawerProduct !== null;
    const url = isUpdate ? `/api/_/products/${drawerProduct!.product.id}` : '/api/_/products';
    const submitData: Partial<Product> = {
      ...formData,
      amount: parseFloat(amountDisplay) || 0
    };
    
    const result = await saveData<Product>(url, submitData, isUpdate, 'Product saved', 'Failed to save product');
    if (result) {
      if (isUpdate) {
        updateProductInList(result);
      } else {
        await loadProducts();
      }
      closeDrawer();
    } else if (isUpdate && drawerProduct) {
      const updatedProduct = await loadData<Product>(`/api/_/products/${drawerProduct.product.id}`, 'Failed to load product');
      if (updatedProduct) {
        updateProductInList(updatedProduct);
      }
    }
  }

  async function handleDeleteProduct() {
    if (!fullProductData || !confirmDelete('product', fullProductData.name)) {
      return;
    }

    const success = await deleteData(
      `/api/_/products/${fullProductData.id}`,
      'Product deleted',
      'Failed to delete product'
    );
    if (success) {
      await loadProducts();
      closeDrawer();
    }
  }

  async function toggleActiveInEdit() {
    if (!fullProductData) return;
    
    const newActive = !fullProductData.active;
    const updatedProduct = { ...fullProductData, active: newActive };
    updateProductInList(updatedProduct);
    
    const result = await toggleActiveApi(
      `/api/_/products/${fullProductData.id}/active`,
      'Product status updated',
      'Failed to update product'
    );
    
    if (result === null) {
      updateProductInList(fullProductData);
    } else {
      const serverProduct = await loadData<Product>(`/api/_/products/${fullProductData.id}`, 'Failed to load product');
      if (serverProduct) {
        updateProductInList(serverProduct);
      }
    }
  }

  function addMetadataRecord() {
    formData.metadata = [...(formData.metadata || []), { key: '', value: '' }];
  }

  function deleteMetadataRecord(index: number) {
    formData.metadata = (formData.metadata || []).filter((_, i) => i !== index);
  }

  function addAttributeRecord() {
    formData.attributes = [...(formData.attributes || []), ''];
  }

  function deleteAttributeRecord(index: number) {
    formData.attributes = (formData.attributes || []).filter((_, i) => i !== index);
  }

  async function deleteProductImage(index: number) {
    if (!fullProductData || !productImages || !productImages[index]) return;
    
    try {
      const imageId = productImages[index].id;
      const res = await apiDelete(`/api/_/products/${fullProductData.id}/image/${imageId}`);
      if (res.success && productImages) {
        productImages = productImages.filter((_, i) => i !== index);
        showMessage('Image deleted', 'connextSuccess');
      } else {
        showMessage(res.message || 'Failed to delete image', 'connextError');
      }
    } catch (error) {
      showMessage('Network error', 'connextError');
    }
  }

  async function handleDelete(product: Product, index: number) {
    if (!confirmDelete('product', product.name)) {
      return;
    }

    const success = await deleteData(
      `/api/_/products/${product.id}`,
      'Product deleted',
      'Failed to delete product'
    );
    if (success) {
      await loadProducts();
    }
  }

  async function toggleActive(product: Product, index: number) {
    const originalActive = product.active;
    const newActive = !product.active;
    products = products.map((p, i) => 
      i === index ? { ...p, active: newActive } : p
    );
    
    try {
      const res = await apiUpdate(`/api/_/products/${product.id}/active`, {});
      if (!res.success) {
        products = products.map((p, i) => 
          i === index ? { ...p, active: originalActive } : p
        );
        showMessage(res.message || 'Failed to update product', 'connextError');
      } else {
        showMessage(res.message || 'Product status updated', 'connextSuccess');
      }
    } catch (error) {
      products = products.map((p, i) => 
        i === index ? { ...p, active: originalActive } : p
      );
      showMessage('Network error', 'connextError');
    }
  }

  function digitalTypeIco(type: string | undefined): string {
    if (!type) return 'cube-transparent';
    switch (type) {
      case 'file':
        return 'paper-clip';
      case 'data':
        return 'queue-list';
      default:
        return 'cube-transparent';
    }
  }

  async function updateActive(index: number) {
    await toggleActive(products[index], index);
  }

  function handleEditorUpdate(event: CustomEvent) {
    formData.description = event.detail;
  }

  function handleUpload(event: CustomEvent) {
    if (event.detail.success) {
      showMessage('File uploaded', 'connextSuccess');
      if (event.detail.result && fullProductData) {
        productImages = [...(productImages || []), event.detail.result];
      }
      loadProducts();
    }
  }
</script>

<svelte:component this={Main}>
  <div class="flex items-center justify-between mb-5">
    <h1>Products</h1>
    <FormButton name="Add Product" color="green" ico="plus" on:click={openAdd} />
  </div>

  {#if loading}
    <div class="text-center py-8">Loading...</div>
  {:else if products.length === 0}
    <div class="text-center py-8 text-gray-500">No products found</div>
  {:else}
    <table>
      <thead>
        <tr>
          <th class="w-28"></th>
          <th>Name</th>
          <th class="w-32">Slug</th>
          <th class="w-32">Price</th>
          <th class="w-12 px-4 py-2">
            <SvgIcon name="cube" className="h-5 w-5" stroke="currentColor" />
          </th>
          <th class="w-24 px-4 py-2"></th>
        </tr>
      </thead>
      <tbody>
        {#each products as product, index}
          <tr class:opacity-30={!product.active}>
            <td>
              {#if product.images && product.images.length > 0}
                <a href="/uploads/{product.images[0].name}.{product.images[0].ext}" target="_blank">
                  <img style="width: 100%; max-width: 80px" src="/uploads/{product.images[0].name}_sm.{product.images[0].ext}" alt={product.name} loading="lazy" />
                </a>
              {:else}
                <img style="width: 100%; max-width: 80px" src="/assets/img/noimage.png" alt="" loading="lazy" />
              {/if}
            </td>
            <td on:click={() => openView(product, index)}>
              <div class="font-bold">{product.name}</div>
              {#if product.brief}
                <span class="text-gray-400 hidden xl:block">{product.brief}</span>
              {/if}
            </td>
            <td>
              {#if product.active}
                <a href="/products/{product.slug}" target="_blank">{product.slug}</a>
              {:else}
                <span>{product.slug}</span>
              {/if}
            </td>
            <td on:click={() => openView(product, index)}>
              {costFormat(product.amount)} {currency}
            </td>
            <td class="px-4 py-2">
              {#if product.digital && product.digital.type}
                <SvgIcon 
                  name={digitalTypeIco(product.digital.type)} 
                  className="h-5 w-5 cursor-pointer {product.digital.filled === true ? 'text-black' : 'text-red-600'}" 
                  on:click={() => openDigital(product, index)} 
                  stroke="currentColor"
                />
              {/if}
            </td>
            <td class="px-4 py-2">
              <div class="flex">
                <div class="pr-3">
                  <SvgIcon 
                    name="pencil-square" 
                    className="h-5 w-5 cursor-pointer" 
                    on:click={() => openEdit(product, index)} 
                    stroke="currentColor"
                  />
                </div>
                <div class="pr-3">
                  <SvgIcon 
                    name="rocket" 
                    className="h-5 w-5 cursor-pointer" 
                    on:click={() => openSeo(product, index)} 
                    stroke="currentColor"
                  />
                </div>
                <div>
                  <SvgIcon 
                    name={product.active ? 'eye' : 'eye-slash'} 
                    className="h-5 w-5 cursor-pointer" 
                    on:click={() => toggleActive(product, index)} 
                    stroke="currentColor"
                  />
                </div>
              </div>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</svelte:component>

{#if drawerOpen}
  <Drawer isOpen={drawerOpen} on:close={closeDrawer} maxWidth="710px">
    {#if drawerMode === 'view' && drawerProduct}
      <ProductView drawer={drawerProduct} {updateActive} on:close={closeDrawer} />
    {:else if drawerMode === 'seo' && drawerProduct}
      <ProductSeo drawer={drawerProduct} on:close={closeDrawer} />
    {:else if drawerMode === 'digital' && drawerProduct}
      <ProductDigital drawer={drawerProduct} onContentUpdate={handleDigitalContentUpdate} on:close={closeDrawer} />
    {:else}
      <div>
        <div class="pb-8">
          <div class="flex items-center">
            <div class="pr-3">
              <h1>{drawerMode === 'add' ? 'Add' : `Edit ${formData.name || ''}`}</h1>
            </div>
            {#if drawerMode === 'edit' && fullProductData}
              <div>
                <SvgIcon 
                  name={fullProductData.active ? 'eye' : 'eye-slash'} 
                  className="h-5 w-5 cursor-pointer" 
                  on:click={toggleActiveInEdit} 
                  stroke="currentColor"
                />
              </div>
            {/if}
          </div>
        </div>

        <form on:submit|preventDefault={handleSubmit}>
          <div class="flow-root">
            <dl class="-my-3 mx-auto mb-0 mt-2 space-y-4 text-sm">
              <FormInput
                id="name"
                title="Name"
                bind:value={formData.name}
                error={formErrors.name}
                ico="at-symbol"
              />
              <div class="flex flex-row">
                <div class="pr-3">
                  <FormInput
                    id="amount"
                    type="text"
                    title="Amount"
                    bind:value={amountDisplay}
                    error={formErrors.amount}
                    ico="money"
                  />
                </div>
                <div class="mt-3">{currency}</div>
              </div>

              {#if drawerMode === 'add'}
                <div class="flex">
                  <div class="grow pr-3">
                    <FormInput
                      id="slug"
                      title="Slug"
                      bind:value={formData.slug}
                      error={formErrors.slug}
                      ico="glob-alt"
                    />
                  </div>
                  <div class="grow">
                    <FormSelect
                      id="digital_type"
                      title="Digital type"
                      options={['file', 'data', 'api']}
                      bind:value={formData.digital.type}
                      error={formErrors.digital_type}
                      ico="cube"
                    />
                  </div>
                </div>
              {:else}
                <FormInput
                  id="slug"
                  title="Slug"
                  bind:value={formData.slug}
                  error={formErrors.slug}
                  ico="glob-alt"
                />
              {/if}

              <hr />
              <p class="font-semibold">Metadata</p>
              {#each formData.metadata || [] as metadata, index}
                <div class="flex">
                  <div class="grow pr-3">
                    <FormInput
                      id="mtd-key-{index}"
                      type="text"
                      title="Key"
                      bind:value={metadata.key}
                    />
                  </div>
                  <div class="grow">
                    <FormInput
                      id="mtd-value-{index}"
                      type="text"
                      title="Value"
                      bind:value={metadata.value}
                    />
                  </div>
                  <div class="flex-none cursor-pointer pl-3 pt-3" role="button" tabindex="0" on:click={() => deleteMetadataRecord(index)} on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); deleteMetadataRecord(index); } }}>
                    <SvgIcon name="trash" className="h-5 w-5" stroke="currentColor" />
                  </div>
                </div>
              {/each}
              <div class="flex">
                <div class="grow"></div>
                <div class="mt-2 flex-none">
                  <button type="button" class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" on:click={addMetadataRecord}>
                    Add metadata record
                  </button>
                </div>
              </div>

              <hr />
              <p class="font-semibold">Attributes</p>
              {#each formData.attributes || [] as attribute, index}
                <div class="flex">
                  <div class="grow">
                    <FormInput
                      id="atr-key-{index}"
                      type="text"
                      title=""
                      bind:value={formData.attributes[index]}
                    />
                  </div>
                  <div class="flex-none cursor-pointer pl-3 pt-3" role="button" tabindex="0" on:click={() => deleteAttributeRecord(index)} on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); deleteAttributeRecord(index); } }}>
                    <SvgIcon name="trash" className="h-5 w-5" stroke="currentColor" />
                  </div>
                </div>
              {/each}
              <div class="flex">
                <div class="grow"></div>
                <div class="mt-2 flex-none">
                  <button type="button" class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" on:click={addAttributeRecord}>
                    Add attribute record
                  </button>
                </div>
              </div>

              {#if drawerMode === 'edit' && fullProductData}
                <hr />
                <p class="font-semibold">Images</p>
                {#if productImages && productImages.length > 0}
                  <div class="grid grid-cols-4 content-start gap-4">
                    {#each productImages as image, index}
                      <div class="relative" style="width: 100%; max-width: 150px">
                        <a href="/uploads/{image.name}.{image.ext}" target="_blank">
                          <img src="/uploads/{image.name}_sm.{image.ext}" alt="" />
                        </a>
                        <div 
                          role="button" 
                          tabindex="0"
                          class="absolute end-4 top-4 cursor-pointer bg-white p-2" 
                          on:click={() => deleteProductImage(index)}
                          on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); deleteProductImage(index); } }}
                        >
                          <SvgIcon name="trash" className="h-5 w-5" stroke="currentColor" />
                        </div>
                      </div>
                    {/each}
                  </div>
                {/if}
                <Upload
                  section="image"
                  productId={fullProductData.id}
                  accept=".jpg,.jpeg,.png"
                  on:added={handleUpload}
                />
              {/if}

              <hr />
              <p class="font-semibold">Short description</p>
              <FormTextarea
                id="brief"
                title="Brief"
                bind:value={formData.brief}
              />

              <hr />
              <p class="font-semibold">Description</p>
              <Editor
                bind:modelValue={formData.description}
                placeholder="type description here"
                on:update:modelValue={handleEditorUpdate}
              />
            </dl>
          </div>

          <div class="pt-8">
            <div class="flex">
              <div class="flex-none">
                <FormButton type="submit" name={drawerMode === 'add' ? 'Add' : 'Save'} color="green" />
                <FormButton type="button" name="Close" color="gray" on:click={closeDrawer} />
              </div>
              <div class="grow"></div>
              {#if drawerMode === 'edit' && fullProductData}
                <div class="mt-2 flex-none">
                  <span on:click={handleDeleteProduct} on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); handleDeleteProduct(); } }} role="button" tabindex="0" class="cursor-pointer text-red-700">Delete</span>
                </div>
              {/if}
            </div>
          </div>
        </form>
      </div>
    {/if}
  </Drawer>
{/if}

// web/admin/src/pages/Products.vue
<template>
  <MainLayouts>
    <header>
      <h1>Products</h1>
      <div>
        <FormButton type="submit" name="Add" color="green" ico="arrow-right" @click="openDrawer(null, null, 'add')" />
      </div>
    </header>

    <div class="mx-auto" v-if="products.total > 0">
      <table>
        <thead>
          <tr>
            <th class="w-28"></th>
            <th>Name</th>
            <th class="w-32">URL</th>
            <th class="w-32">Price</th>
            <th class="w-24 px-4 py-2"></th>
          </tr>
        </thead>
        <tbody>
          <tr :class="{ 'opacity-30': !item.active }" v-for="(item, index) in products.products">
            <td>
              <a :href="`/uploads/${item.images[0].name}.${item.images[0].ext}`" target="_blank" v-if="item.images">
                <img style="width: 100%; max-width: 80px" :src="`/uploads/${item.images[0].name}_sm.${item.images[0].ext}`" loading="lazy" />
              </a>
              <img style="width: 100%; max-width: 80px" src="/assets/img/noimage.png" v-else />
            </td>
            <td @click="openDrawer(index, item.id, 'view')">
              <div>{{ item.name }}</div>
            </td>
            <td>
              <a :href="`/products/${item.url}`" target="_blank" v-if="item.active">{{ item.url }}</a>
              <span v-else>{{ item.url }}</span>
            </td>
            <td @click="openDrawer(index, item.id, 'view')">
              {{ costFormat(item.amount) }} {{ products.currency }}
            </td>
            <td class="px-4 py-2">
              <div class="flex">
                <div class="pr-3">
                  <SvgIcon name="pencil-square" class="h-5 w-5" @click="openDrawer(index, item.id, 'update')" />
                </div>
                <div>
                  <SvgIcon :name="item.active ? 'eye' : 'eye-slash'" class="h-5 w-5" @click="updateProductActive(index)" />
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="mx-auto" v-else>Add first product</div>

    <drawer :is-open="isDrawer.open" max-width="700px" @close="closeDrawer">
      <!-- Start view section -->
      <div v-if="isDrawer.action === 'view'">
        <div class="pb-8">
          <div class="flex items-center">
            <div class="pr-3">
              <h1>View {{ products.products[product.index].name }}</h1>
            </div>
            <div>
              <SvgIcon :name="products.products[product.index].active ? 'eye' : 'eye-slash'" class="h-5 w-5 cursor-pointer" @click="updateProductActive(product.index)" />
            </div>
          </div>
        </div>

        <div class="flow-root">
          <dl class="-my-3 divide-y divide-gray-100 text-sm">
            <DetailList name="ID">{{ product.info.id }}</DetailList>
            <DetailList name="Name">{{ product.info.name }}</DetailList>
            <DetailList name="Price">{{ product.info.amount }} {{ products.currency }}</DetailList>
            <DetailList name="URL">{{ product.info.url }}</DetailList>
            <DetailList name="Metadata">
              <div v-for="(data, index) in product.info.metadata">{{ data.key }}: {{ data.value }}</div>
            </DetailList>
            <DetailList name="Attributes">
              <div v-for="item in product.info.attributes">{{ item }}</div>
            </DetailList>
            <DetailList name="Created">{{ formatDate(product.info.created) }}</DetailList>
            <DetailList name="Updated" v-if="product.info.updated">{{ formatDate(product.info.updated) }}</DetailList>
            <DetailList name="Images" :grid="true" v-if="product.info.images">
              <div v-for="item in product.info.images">
                <a :href="`/uploads/${item.name}.${item.ext}`" target="_blank">
                  <img style="width: 100%; max-width: 150px" :src="`/uploads/${item.name}_sm.${item.ext}`" loading="lazy" />
                </a>
              </div>
            </DetailList>

            <DetailList name="description">{{ product.info.description }}</DetailList>
          </dl>
        </div>

        <div class="pt-8">
          <FormButton type="submit" name="Close" color="green" @click="closeDrawer" />
        </div>
      </div>
      <!-- End view section -->

      <!-- Start update section -->
      <div v-if="isDrawer.action === 'update'">
        <div class="pb-8">
          <div class="flex items-center">
            <div class="pr-3">
              <h1>Edit {{ products.products[product.index].name }}</h1>
            </div>
            <div>
              <SvgIcon :name="products.products[product.index].active ? 'eye' : 'eye-slash'" class="h-5 w-5 cursor-pointer" @click="updateProductActive(product.index)" />
            </div>
          </div>
        </div>

        <Form @submit="updateProduct" v-slot="{ errors }">
          <div class="flow-root" v-if="isDrawer.action === 'update'">
            <dl class="-my-3 text-sm mx-auto mb-0 mt-4 space-y-4">
              <FormInput v-model.trim="product.info.name" :error="errors.name" rules="required|min:4" id="name" type="text" title="Name" ico="at-symbol" />

              <div class="flex flex-row">
                <div class="pr-3">
                  <FormInput v-model.trim="product.info.amount" :error="errors.amount" rules="required|amount" id="amount" type="text" title="Amount" ico="money" />
                </div>
                <div class="mt-3">{{ products.currency }}</div>
              </div>
              <FormInput v-model.trim="product.info.url" :error="errors.url" rules="required|alpha_num" id="url" type="text" title="Url" ico="glob-alt" />

              <hr />
              <p class="font-semibold">Metadata</p>
              <div class="flex" v-for="(data, index) in product.info.metadata" :key="index">
                <div class="grow pr-3">
                  <FormInput v-model="data.key" :id="`mtd-key-${index}`" type="text" title="" />
                </div>
                <div class="grow">
                  <FormInput v-model="data.value" :id="`mtd-value-${index}`" type="text" title="" />
                </div>
                <div class="flex-none cursor-pointer pl-3 pt-3" @click="deleteMetadataRecord(index)">
                  <SvgIcon name="trash" class="h-5 w-5" />
                </div>
              </div>
              <div class="flex">
                <div class="grow"></div>
                <div class="mt-2 flex-none">
                  <a href="#" class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" @click="addMetadataRecord()">
                    Add metadata record
                  </a>
                </div>
              </div>

              <hr />
              <p class="font-semibold">Attributes</p>
              <div class="flex" v-for="(value, index) in product.info.attributes" :key="index">
                <div class="grow">
                  <FormInput v-model="product.info.attributes[index]" :id="`atr-key-${index}`" type="text" title="" />
                </div>
                <div class="flex-none cursor-pointer pl-3 pt-3" @click="deleteAttributeRecord(index)">
                  <SvgIcon name="trash" class="h-5 w-5" />
                </div>
              </div>
              <div class="flex">
                <div class="grow"></div>
                <div class="mt-2 flex-none">
                  <a href="#" class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" @click="addAttributeRecord()">
                    Add attribute record
                  </a>
                </div>
              </div>

              <hr />
              <p class="font-semibold">Images</p>
              <div class="grid grid-cols-4 content-start gap-4" v-if="product.info.images !== null">
                <div v-for="(item, index) in product.info.images" class="relative" style="width: 100%; max-width: 150px">
                  <a :href="`/uploads/${item.name}.${item.ext}`" target="_blank">
                    <img :src="`/uploads/${item.name}_sm.${item.ext}`" />
                  </a>
                  <div class="absolute end-4 top-4 cursor-pointer bg-white p-2" @click="deleteProductImage(index, product.info.id)">
                    <SvgIcon name="trash" class="h-5 w-5" />
                  </div>
                </div>
              </div>
              <FormUpload :productId="`${product.info.id}`" accept=".jpg,.jpeg,.png" @added="addProductImage" />

              <hr />
              <FormTextarea v-model="product.info.description" id="textarea" name="Description" />
            </dl>
          </div>

          <div class="pt-8">
            <div class="flex">
              <div class="flex-none">
                <FormButton type="submit" name="Save" color="green" class="mr-3" />
                <FormButton type="submit" name="Close" color="gray" @click="closeDrawer" />
              </div>
              <div class="grow"></div>
              <div class="mt-2 flex-none">
                <span @click="deleteProduct(product.index)" class="cursor-pointer text-red-700">Delete</span>
              </div>
            </div>
          </div>
        </Form>
      </div>
      <!-- End update section -->

      <!-- Start add section -->
      <div v-if="isDrawer.action === 'add'">
        <div class="pb-8">
          <div class="flex items-center">
            <div class="pr-3">
              <h1>Add</h1>
            </div>
          </div>
        </div>

        <Form @submit="addProduct" v-slot="{ errors }">
          <div class="flow-root" v-if="isDrawer.action === 'add'">
            <dl class="-my-3 text-sm mx-auto mb-0 mt-4 space-y-4">
              <FormInput v-model.trim="product.info.name" :error="errors.name" rules="required|min:4" id="name" type="text" title="Name" ico="at-symbol" />
              <div class="flex flex-row">
                <div class="pr-3">
                  <FormInput v-model.trim="product.info.amount" :error="errors.amount" rules="required|amount" id="amount" type="text" title="Amount" ico="money" />
                </div>
                <div class="mt-3">{{ products.currency }}</div>
              </div>
              <FormInput v-model.trim="product.info.url" :error="errors.url" rules="required|alpha_num" id="url" type="text" title="Url" ico="glob-alt" />

              <hr />
              <p class="font-semibold">Metadata</p>
              <div class="flex" v-for="(data, index) in product.info.metadata" :key="index">
                <div class="grow pr-3">
                  <FormInput v-model="data.key" :id="`mtd-key-${index}`" type="text" title="" />
                </div>
                <div class="grow">
                  <FormInput v-model="data.value" :id="`mtd-value-${index}`" type="text" title="" />
                </div>
                <div class="flex-none cursor-pointer pl-3 pt-3" @click="deleteMetadataRecord(index)">
                  <SvgIcon name="trash" class="h-5 w-5" />
                </div>
              </div>
              <div class="flex">
                <div class="grow"></div>
                <div class="mt-2 flex-none">
                  <a href="#" class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" @click="addMetadataRecord">
                    Add metadata record
                  </a>
                </div>
              </div>

              <hr />
              <p class="font-semibold">Attributes</p>
              <div class="flex" v-for="(value, index) in product.info.attributes" :key="index">
                <div class="grow">
                  <FormInput v-model="product.info.attributes[index]" :id="`atr-key-${index}`" type="text" title="" />
                </div>
                <div class="flex-none cursor-pointer pl-3 pt-3" @click="deleteAttributeRecord(index)">
                  <SvgIcon name="trash" class="h-5 w-5" />
                </div>
              </div>
              <div class="flex">
                <div class="grow"></div>
                <div class="mt-2 flex-none">
                  <a href="#" class="shrink-0 rounded-lg bg-gray-200 p-2 text-sm font-medium text-gray-700" @click="addAttributeRecord">
                    Add attribute record
                  </a>
                </div>
              </div>

              <hr />
              <FormTextarea v-model="product.info.description" id="textarea" name="Description" />

            </dl>
          </div>

          <div class="pt-8">
            <div class="flex">
              <div class="flex-none">
                <FormButton type="submit" name="Add" color="green" class="mr-3" />
                <FormButton type="submit" name="Close" color="gray" @click="closeDrawer" />
              </div>
              <div class="grow"></div>
            </div>
          </div>
        </Form>
      </div>
      <!-- End update section -->
    </drawer>
  </MainLayouts>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { notify } from "notiwind";
import * as NProgress from "nprogress";
import SvgIcon from "svg-icon";
import { defineRule, Form } from "vee-validate";
import { required, numeric, alpha_num, min } from "@vee-validate/rules";
defineRule("required", required);
defineRule("min", min);
defineRule("numeric", numeric);
defineRule("alpha_num", alpha_num);
defineRule('amount', value => {
  if (!value || !value.length) {
    return true;
  }
  if (!/^\d+(\.\d{1,2})?$/.test(value)) {
    return 'amount is not valid';
  }
  return true;
});

import { costFormat, costStripe, formatDate } from "@/utils/";

import MainLayouts from "@/layouts/Main.vue";
import FormInput from "@/components/form/Input.vue";
import FormButton from "@/components/form/Button.vue";
import FormUpload from "@/components/form/Upload.vue";
import FormTextarea from "@/components/form/Textarea.vue";
import DetailList from "@/components/DetailList.vue";
import Drawer from "@/components/Drawer.vue";

onMounted(() => {
  listProducts();
});

const isDrawer = ref({
  open: false,
  action: null,
});

const products = ref([]);

const product = ref({
  info: {},
  action: null,
  index: 0,
  name: null,
});

const listProducts = async () => {

  try {
    const response = await fetch("/api/_/products", {
      credentials: "include",
      method: "GET",
    });
    const data = await response.json();

    if (data.success) {
      products.value = data.result;
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const getProduct = async (id) => {
  try {
    NProgress.start();

    const response = await fetch(`/api/_/products/${id}`, {
      credentials: "include",
      method: "GET",
    });
    const data = await response.json();

    if (data.success) {
      const { info } = product.value;
      Object.assign(info, data.result);
      info.amount = costFormat(info.amount);
    } else {
      notify({
        group: "bottom",
        title: "Error",
        text: data.result,
      }, 4000)
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const updateProduct = async () => {
  try {
    const update = { ...product.value.info };
    update.amount = costStripe(update.amount);

    NProgress.start();

    const response = await fetch(`/api/_/products/${update.id}`, {
      credentials: "include",
      method: "PATCH",
      body: JSON.stringify(update),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await response.json();

    if (data.success) {
      const found = products.value.products.find((e) => e.id === update.id);
      found.name = update.name;
      found.url = update.url;
      found.amount = update.amount;
      found.description = update.description;
      closeDrawer();
    } else {
      notify({
        group: "bottom",
        title: "Error",
        text: data.result,
      }, 4000)
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const addProduct = async () => {
  try {
    const add = { ...product.value.info };
    add.amount = costStripe(add.amount);

    NProgress.start();

    const response = await fetch(`/api/_/products`, {
      credentials: "include",
      method: "POST",
      body: JSON.stringify(add),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await response.json();

    if (data.success) {
      products.value.products.push({
        id: data.result.id,
        name: data.result.name,
        description: data.result.description,
        amount: data.result.amount,
        url: data.result.url,
        created: data.result.created,
      });
      products.value.total++;
      closeDrawer();
    } else {
      notify({
        group: "bottom",
        title: "Error",
        text: data.result,
      }, 4000)
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const deleteProduct = async (index) => {
  try {
    NProgress.start();

    const response = await fetch(`/api/_/products/${products.value.products[index].id}`, {
      credentials: "include",
      method: "DELETE",
    });
    const data = await response.json();

    if (data.success) {
      products.value.products.splice(index, 1);
      products.value.total--;
    } else {
      const obj = JSON.parse(data.result);
      if (obj.code === "resource_missing") {
        console.log(obj.message);
      }
    }

    closeDrawer();
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const updateProductActive = async (index) => {
  NProgress.start();

  try {
    const response = await fetch(`/api/_/products/${products.value.products[index].id}/active`, {
      credentials: "include",
      method: "PATCH",
    });
    const data = await response.json();

    if (data.success) {
      products.value.products[index].active = !products.value.products[index].active;
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const addMetadataRecord = () => {
  const metadata = product.value.info.metadata || [];
  metadata.push({ key: "", value: "" });
  product.value.info.metadata = metadata;
};

const deleteMetadataRecord = (key) => {
  product.value.info.metadata.splice(key, 1);
};

const addAttributeRecord = () => {
  const attributes = product.value.info.attributes || [];
  attributes.push("");
  product.value.info.attributes = attributes;
};

const deleteAttributeRecord = (index) => {
  product.value.info.attributes.splice(index, 1);
};

const addProductImage = (event) => {
  if (event.success) {
    product.value.info.images.push(event.result);
  }
};

const deleteProductImage = async (index, productId) => {
  try {
    NProgress.start();
    const image = product.value.info.images[index];

    const response = await fetch(`/api/_/products/${productId}/image/${image.id}`, {
      credentials: "include",
      method: "DELETE",
    });
    const data = await response.json();

    if (data.success) {
      product.value.info.images.splice(index, 1);
    } else {
      notify({
        group: "bottom",
        title: "Error",
        text: data.result,
      }, 4000)
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const openDrawer = (index, id, action) => {
  isDrawer.value.open = true;
  isDrawer.value.action = action;
  product.value.index = index;

  switch (action) {
    case "view":
    case "update":
      getProduct(id);
      break;
    case "add":
      product.value.info.metadata = [];
      product.value.info.attributes = [];
      product.value.info.description = "";
      break;
  }
};

const closeDrawer = () => {
  isDrawer.value.open = false;
  isDrawer.value.action = null;
  product.value.info = {};
  product.value.index = null;
};
</script>
