// web/admin/src/components/setting/Letter.vue
<template>
  <div>
    <div class="pb-8">
      <div class="flex items-center">
        <div class="pr-3">
          <h1>Update letter</h1>
        </div>
      </div>
    </div>
    <div class="flow-root">

      <div class="flow-root">
        <dl class="-my-3 mx-auto mb-0 mt-2 space-y-4 text-sm">
          <FormInput v-model.trim="letter.subject" id="subject" type="text" title="Subject" @focusout="updateLetter" />
        </dl>
      </div>

      <dl class="-my-3 mx-auto mb-0 space-y-4 text-sm mt-5">
        <FormTextarea v-model="letter.text" id="textarea" name="Message" :rows="15" @focusout="updateLetter" />
      </dl>
    </div>

    <div class="pt-8">
      <div class="flex">
        <div class="flex-none">
          <FormButton type="submit" name="Close" color="gray" @click="close" />
        </div>
        <div class="grow"></div>
        <div class="flex-none">
          <FormButton type="submit" name="Test letter" color="cyan" @click="send(name)" />
        </div>
      </div>
    </div>

    <table class="mt-8 text-base">
      <tbody>
        <tr v-for="(value, key) in legend" class="cursor-default">
          <td class="w-32 font-bold">&#123;&#123;.{{ key }}&#125;&#125;</td>
          <td>{{ value }}</td>
        </tr>
      </tbody>
    </table>

  </div>
</template>

<script setup>
import { onMounted, ref } from "vue";
import FormInput from "@/components/form/Input.vue";
import FormTextarea from "@/components/form/Textarea.vue";
import FormButton from "@/components/form/Button.vue";
import { showMessage } from "@/utils/message";
import { apiGet, apiUpdate } from "@/utils/api";

const props = defineProps({
  name: String,
  legend: Object,
  send: Function,
  close: Function,
});

onMounted(() => {
  settingLetter();
});

const letter = ref({});

const settingLetter = async () => {
  apiGet(`/api/_/settings/${props.name}`).then(res => {
    if (res.success) {
      letter.value.id = res.result.id;
      letter.value.key = res.result.key;
      letter.value.subject = JSON.parse(res.result.value).subject;
      letter.value.text = JSON.parse(res.result.value).text;
      letter.value.html = JSON.parse(res.result.value).html;
    }
  });
};

const updateLetter = async () => {
  console.log("xx")

  const value = new Object();
  value.subject = letter.value.subject;
  value.text = letter.value.text;
  value.html = letter.value.html;

  const update = {
    id: letter.value.id,
    key: letter.value.key,
    value: JSON.stringify(value),
  };

  apiUpdate(`/api/_/settings/${props.name}`, update).then(res => {
    if (res.success) {
      showMessage(res.message);
      //props.close();
    } else {
      showMessage(res.result, "connextError");
    }
  });
};

</script>

// web/admin/src/lib/components/setting/Letter.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { createEventDispatcher } from 'svelte'
  import FormButton from '../form/Button.svelte'
  import FormInput from '../form/Input.svelte'
  import FormTextarea from '../form/Textarea.svelte'
  import { loadData, saveData } from '$lib/utils/apiHelpers'
  import type { LetterData, LetterContent } from '$lib/types/models'

  export let name: string
  export let legend: Record<string, string>

  const dispatch = createEventDispatcher()

  interface SettingResponse {
    id?: string
    key?: string
    value?: string | LetterContent
    [key: string]: unknown
  }

  let letter: LetterData & LetterContent = {
    id: '',
    key: '',
    subject: '',
    text: '',
    html: ''
  }
  let loading = true

  onMount(async () => {
    await loadLetter()
  })

  async function loadLetter() {
    if (!name) return

    loading = true
    const result = await loadData<SettingResponse | Record<string, SettingResponse>>(
      `/api/_/settings/${name}`,
      'Failed to load letter'
    )

    if (result) {
      const setting =
        (result as Record<string, SettingResponse>)[name] ||
        ((result as SettingResponse).id
          ? (result as SettingResponse)
          : Object.values(result as Record<string, SettingResponse>)[0])

      if (setting) {
        letter.id = setting.id || ''
        letter.key = setting.key || name

        if (setting.value) {
          const value = typeof setting.value === 'string' ? JSON.parse(setting.value) : setting.value
          letter.subject = value.subject || ''
          letter.text = value.text || ''
          letter.html = value.html || ''
        }
      }
    }
    loading = false
  }

  async function updateLetter() {
    const value: LetterContent = {
      subject: letter.subject,
      text: letter.text,
      html: letter.html
    }

    const update: LetterData = {
      id: letter.id,
      key: letter.key,
      value: JSON.stringify(value)
    }

    await saveData<LetterData>(`/api/_/settings/${name}`, update, true, 'Letter updated', 'Failed to update letter')
  }

  function handleSend() {
    dispatch('send', name)
  }

  function close() {
    dispatch('close')
  }

  function getTemplateKey(key: string): string {
    return `{{.${key}}}`
  }
</script>

<div>
  <div class="pb-8">
    <div class="flex items-center">
      <div class="pr-3">
        <h1>Update letter</h1>
      </div>
    </div>
  </div>

  {#if loading}
    <div class="py-8 text-center">Loading...</div>
  {:else}
    <div class="flow-root">
      <div class="flow-root">
        <dl class="mx-auto -my-3 mt-2 mb-0 space-y-4 text-sm">
          <FormInput id="subject" type="text" title="Subject" bind:value={letter.subject} on:focusout={updateLetter} />
        </dl>
      </div>

      <dl class="mx-auto -my-3 mt-5 mb-0 space-y-4 text-sm">
        <FormTextarea id="textarea" title="Message" bind:value={letter.text} rows={15} on:focusout={updateLetter} />
      </dl>
    </div>
  {/if}

  <div class="pt-8">
    <div class="flex">
      <div class="flex-none">
        <FormButton type="button" name="Close" color="gray" on:click={close} />
      </div>
      <div class="grow"></div>
      <div class="flex-none">
        <FormButton type="button" name="Test letter" color="cyan" on:click={handleSend} />
      </div>
    </div>
  </div>

  <table class="mt-8 text-base">
    <tbody>
      {#each Object.entries(legend) as [key, value]}
        <tr class="cursor-default">
          <td class="w-32 font-bold">{getTemplateKey(key)}</td>
          <td>{value}</td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>
