// web/admin/src/lib/components/form/Input.svelte
<script lang="ts">
  import SvgIcon from '../SvgIcon.svelte'

  export let id: string = 'name'
  export let type: string = 'text'
  export let title: string = 'Name'
  export let ico: string | undefined = undefined
  export let error: string | undefined = undefined
  export let value: string = ''
  export let placeholder: string = ''

  $: computedPlaceholder = placeholder || `Enter ${id}`
</script>

<div>
  <label for={id} class={error ? 'border-red-500' : ''}>
    <input
      {type}
      {id}
      bind:value
      class="form-input field peer"
      placeholder={computedPlaceholder}
      autocomplete="on"
      on:focusout
      on:input
    />
    {#if title}
      <span
        class="title peer-placeholder-shown:top-1/2 peer-placeholder-shown:text-sm peer-placeholder-shown:text-gray-400 peer-focus:top-0 peer-focus:text-xs peer-focus:text-gray-700"
      >
        {title}
      </span>
    {/if}
    {#if ico}
      <span class="ico">
        <SvgIcon name={ico} stroke="currentColor" className="h-5 w-5 {error ? 'text-red-500' : 'text-gray-400'}" />
      </span>
    {/if}
  </label>
  {#if error}
    <span class="pl-4 text-sm text-red-500">{error}</span>
  {/if}
</div>

// web/admin/src/components/form/Input.vue
<template>
  <div>
    <label :for="id" :class="error ? 'border-red-500' : ''">
      <Field :type="type" :name="id" :rules="rules" :id="id" v-model="model" class="form-input field peer" :placeholder="placeholder" autocomplete="on" />
      <span v-if="title" class="peer-placeholder-shown:top-1/2 peer-placeholder-shown:text-sm peer-focus:top-0 peer-focus:text-xs title">
        {{ title }}
      </span>
      <span class="ico" v-if="ico">
        <SvgIcon :name="ico" stroke="currentColor" class="h-5 w-5" :class="error ? 'text-red-500' : 'text-gray-400'" />
      </span>
    </label>
    <span class="text-sm text-red-500 pl-4" v-if="error">{{ error }}</span>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { Field } from 'vee-validate';

const props = defineProps({
  modelValue: {
    required: true
  },
  id: {
    type: String,
    default: 'name'
  },
  type: {
    type: String,
    default: 'text'
  },
  title: {
    type: String,
    default: 'Name'
  },
  color: {
    type: String,
    default: 'indigo'
  },
  rules: String,
  ico: String,
  error: String
})

const placeholder = 'Enter ' + props.id
const emits = defineEmits(['update:modelValue'])
const model = computed({
  get: () => {
    return props.modelValue
  },
  set: (val) => {
    emits('update:modelValue', val)
  }
})
</script>
