// web/admin/src/lib/components/form/Toggle.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'

  export let id: string = 'name'
  export let value: boolean = false
  export let disabled: boolean = false

  const dispatch = createEventDispatcher()

  function handleChange() {
    dispatch('change')
  }
</script>

<label
  for="toggle_{id}"
  class="none relative h-6 w-10 cursor-pointer [-webkit-tap-highlight-color:_transparent]"
  class:opacity-25={disabled}
>
  <input
    type="checkbox"
    id="toggle_{id}"
    bind:checked={value}
    {disabled}
    on:change={handleChange}
    class="peer sr-only [&:checked_+_span_svg[data-checked-icon]]:block [&:checked_+_span_svg[data-unchecked-icon]]:hidden"
  />

  <span
    class="absolute inset-y-0 start-0 z-10 m-1 inline-flex h-4 w-4 items-center justify-center rounded-full bg-white text-gray-400 transition-all peer-checked:start-4 peer-checked:text-green-600"
  >
    <svg data-unchecked-icon xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
      <path
        fill-rule="evenodd"
        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
        clip-rule="evenodd"
      />
    </svg>

    <svg
      data-checked-icon
      xmlns="http://www.w3.org/2000/svg"
      class="hidden h-3 w-3"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path
        fill-rule="evenodd"
        d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
        clip-rule="evenodd"
      />
    </svg>
  </span>

  <span class="absolute inset-0 rounded-full bg-gray-300 transition peer-checked:bg-green-500"></span>
</label>

// web/admin/src/components/form/Toggle.vue
<template>
  <label :for="`toggle_` + id" class="none relative h-6 w-10 cursor-pointer [-webkit-tap-highlight-color:_transparent]" :class="{ 'opacity-25': disabled }">
    <input type="checkbox" :id="`toggle_` + id" v-model="model" :checked="Boolean(model)" :disabled="disabled"
      class="peer sr-only [&:checked_+_span_svg[data-checked-icon]]:block [&:checked_+_span_svg[data-unchecked-icon]]:hidden" />

    <span
      class="absolute inset-y-0 start-0 z-10 m-1 inline-flex h-4 w-4 items-center justify-center rounded-full bg-white text-gray-400 transition-all peer-checked:start-4 peer-checked:text-green-600">
      <svg data-unchecked-icon xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd"
          d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
          clip-rule="evenodd" />
      </svg>

      <svg data-checked-icon xmlns="http://www.w3.org/2000/svg" class="hidden h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
      </svg>
    </span>

    <span class="absolute inset-0 rounded-full bg-gray-300 transition peer-checked:bg-green-500"></span>
  </label>
</template>

<script setup>
import { computed } from "vue";

const props = defineProps({
  modelValue: {
    required: true,
  },
  id: {
    type: String,
    default: "name",
  },
  disabled: Boolean,
});

const emits = defineEmits(["update:modelValue"]);
const model = computed({
  get: () => {
    return props.modelValue;
  },
  set: (val) => {
    emits("update:modelValue", val);
  },
});
</script>
