// web/admin/src/pages/Pages.vue
<template>
  <MainLayouts>
    <div v-if="!route.params.page_url">
      <header>
        <h1>Pages</h1>
        <div>
          <FormButton type="submit" name="New" color="green" ico="arrow-right" @click="openDrawer(null, 'add')" />
        </div>
      </header>

      <div class="mx-auto" v-if="pages.length > 0">
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th class="w-32">Group</th>
              <th class="w-32">Url</th>
              <th class="w-32">Created</th>
              <th class="w-32">Updated</th>
              <th class="w-24 px-4 py-2"></th>
            </tr>
          </thead>
          <tbody>
            <tr :class="{ 'opacity-30': !item.active }" v-for="(item, index) in pages" :key="item.id">
              <td @click="openPage(item.url)">{{ item.name }}</td>
              <td @click="openPage(item.url)">{{ item.type }}</td>
              <td @click="openPage(item.url)">{{ item.url }}</td>
              <td @click="openPage(item.url)">{{ formatDate(item.created) }}</td>
              <td v-if="item.updated">{{ formatDate(item.updated) }}</td>
              <td v-else></td>
              <td class="px-4 py-2">
                <div class="flex">
                  <div class="pr-3">
                    <SvgIcon name="pencil-square" class="h-5 w-5" @click="openDrawer(index, 'update')" />
                  </div>
                  <div>
                    <SvgIcon :name="item.active ? 'eye' : 'eye-slash'" class="h-5 w-5" @click="updatePageActive(index)" />
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="mx-auto" v-else>Not found pages</div>
    </div>
    <div v-else class="mt-5">
      <header>
        <h1>{{ page.name }}</h1>
      </header>
      <div class="pt-5">
        <Editor v-model="content" />

        <hr class="my-5" />
        <FormButton type="submit" name="Save" color="green" @click="updatePageContent" />
      </div>
    </div>

    <drawer :is-open="isDrawer.open" max-width="700px" @close="closeDrawer">
      <div v-if="isDrawer.action === 'add'">
        <div class="pb-8">
          <div class="flex items-center">
            <div class="pr-3">
              <h1>New page</h1>
            </div>
          </div>
        </div>

        <Form @submit="addPage" v-slot="{ errors }">
          <div class="flow-root">
            <dl class="-my-3 text-sm mx-auto mb-0 mt-4 space-y-4">
              <FormInput v-model.trim="page.name" :error="errors.name" rules="required|min:4" id="name" type="text" title="name" ico="at-symbol" />
              <div class="flex">
                <div class="pr-3">
                  <FormSelect v-model="page.type" :options="typePage" :error="errors.type" rules="required" id="type" title="Type"></FormSelect>
                </div>
                <div>
                  <FormInput v-model.trim="page.url" :error="errors.url" rules="required|alpha_num" id="url" type="text" title="Url" ico="glob-alt" />
                </div>
              </div>

            </dl>
          </div>

          <div class="pt-8">
            <div class="flex">
              <div class="flex-none">
                <FormButton type="submit" name="Add" color="green" class="mr-3" />
                <FormButton type="submit" name="Close" color="gray" @click="closeDrawer" />
              </div>
              <div class="grow"></div>
            </div>
          </div>
        </Form>
      </div>

      <div v-if="isDrawer.action === 'update'">
        <div class="pb-8">
          <div class="flex items-center">
            <div class="pr-3">
              <h1>Page setup</h1>
            </div>
          </div>
        </div>

        <Form @submit="updatePage" v-slot="{ errors }">
          <div class="flow-root">
            <dl class="-my-3 text-sm mx-auto mb-0 mt-4 space-y-4">
              <FormInput v-model.trim="page.name" :error="errors.name" rules="required|min:4" id="name" type="text" title="name" ico="at-symbol" />
              <div class="flex">
                <div class="pr-3">
                  <FormSelect v-model="page.type" :options="typePage" :error="errors.type" rules="required" id="type" title="Type"></FormSelect>
                </div>
                <div>
                  <FormInput v-model.trim="page.url" :error="errors.url" rules="required|alpha_num" id="url" type="text" title="Url" ico="glob-alt" />
                </div>
              </div>

            </dl>
          </div>

          <div class="pt-8">
            <div class="flex">
              <div class="flex-none">
                <FormButton type="submit" name="Save" color="green" class="mr-3" />
                <FormButton type="submit" name="Close" color="gray" @click="closeDrawer" />
              </div>
              <div class="grow"></div>
              <div class="mt-4 flex-none">
                <span @click="deletePage" class="cursor-pointer text-red-700">Delete</span>
              </div>
            </div>
          </div>
        </Form>
      </div>
    </drawer>

  </MainLayouts>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import MainLayouts from "@/layouts/Main.vue";
import { notify } from "notiwind";
import * as NProgress from "nprogress";
import SvgIcon from "svg-icon";

import { defineRule, Form } from "vee-validate";
import { required, alpha_num, min } from "@vee-validate/rules";
defineRule("required", required);
defineRule("alpha_num", alpha_num);
defineRule("min", min);

import { formatDate } from "@/utils/";
import Editor from "@/components/Editor.vue";
import FormInput from "@/components/form/Input.vue";
import FormSelect from "@/components/form/Select.vue";
import FormButton from "@/components/form/Button.vue";
import Drawer from "@/components/Drawer.vue";

const route = useRoute();
const router = useRouter()
const pages = ref([]);

const page = ref({});
const content = ref();

const isDrawer = ref({
  open: false,
  action: null,
});

const typePage = ["header", "footer"];

onMounted(async () => {
  pagesList();

  if (route.params.page_url) {
    pageContent(route.params.page_url)
  }
});

const pagesList = async () => {
  try {
    NProgress.start();

    const response = await fetch(`/api/_/pages`, {
      credentials: "include",
      method: "GET",
    });
    const { success, result } = await response.json();

    if (success) {
      pages.value = result;
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const openPage = (url) => {
  router.push({ name: 'pagesArticle', params: { 'page_url': url } });
  pageContent(url)
}

const pageContent = async (url) => {
  try {
    NProgress.start();

    const response = await fetch(`/api/pages/${url}`, {
      credentials: "include",
      method: "GET",
    });
    const { status } = response;
    const { success, result } = await response.json();

    if (success) {
      page.value = result;
      content.value = result.content;
    }

    if (status == 404) {
      router.push({ name: '404' });
    }

  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const addPage = async () => {
  const add = { ...page.value };
  console.log(add);

  try {
    const response = await fetch(`/api/_/pages`, {
      credentials: "include",
      method: "POST",
      body: JSON.stringify(add),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const { success, result } = await response.json();

    if (success) {
      pages.value.push({
        id: result.id,
        name: result.name,
        url: result.url,
        type: result.type,
        created: result.created,
        active: result.active
      });
      closeDrawer();
    } else {
      notify({
        group: "bottom",
        title: "Error",
        text: result,
      }, 4000)
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
}

const updatePageContent = async () => {
  try {
    NProgress.start();
    page.value.content = content.value;

    const response = await fetch(`/api/_/pages/${page.value.id}/content`, {
      credentials: "include",
      method: "PATCH",
      body: JSON.stringify(page.value),
      headers: {
        "Content-Type": "application/json",
      },
    });
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const updatePageActive = async (index) => {
  try {
    NProgress.start();

    const response = await fetch(`/api/_/pages/${pages.value[index].id}/active`, {
      credentials: "include",
      method: "PATCH",
    });
    const { success } = await response.json();

    if (success) {
      pages.value[index].active = !pages.value[index].active;
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
};

const updatePage = async () => {
  try {
    const update = { ...page.value };
    NProgress.start();

    const response = await fetch(`/api/_/pages/${update.id}`, {
      credentials: "include",
      method: "PATCH",
      body: JSON.stringify(update),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const { success, result } = await response.json();

    if (success) {
      const found = pages.value.find((e) => e.id === update.id);
      found.name = update.name;
      found.url = update.url;
      found.type = update.type;
      closeDrawer();
    } else {
      notify({
        group: "bottom",
        title: "Error",
        text: result,
      }, 4000)
    }
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
}

const deletePage = async () => {
  try {
    const index = page.value.index;
    NProgress.start();

    const response = await fetch(`/api/_/pages/${pages.value[index].id}`, {
      credentials: "include",
      method: "DELETE",
    });
    const { success, result } = await response.json();

    if (success) {
      pages.value.splice(index, 1);
    } else {
      const obj = JSON.parse(result);
      if (obj.code === "resource_missing") {
        console.log(obj.message);
      }
    }

    closeDrawer();
  } catch (error) {
    console.error(error);
  } finally {
    NProgress.done();
  }
}

const openDrawer = (index, action) => {
  page.value = {};
  isDrawer.value.open = true;
  isDrawer.value.action = action;

  if (action === "update") {
    page.value = {
      name: pages.value[index].name,
      url: pages.value[index].url,
      type: pages.value[index].type,
      id: pages.value[index].id,
      index: index,
    }
  }
};

const closeDrawer = () => {
  isDrawer.value.open = false;
  isDrawer.value.action = null;
};
</script>

// web/admin/src/routes/pages/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Main from '$lib/layouts/Main.svelte';
  import Drawer from '$lib/components/Drawer.svelte';
  import PageSeo from '$lib/components/page/Seo.svelte';
  import FormButton from '$lib/components/form/Button.svelte';
  import FormInput from '$lib/components/form/Input.svelte';
  import FormSelect from '$lib/components/form/Select.svelte';
  import Editor from '$lib/components/Editor.svelte';
  import SvgIcon from '$lib/components/SvgIcon.svelte';
  import { loadData, saveData, deleteData, toggleActive as toggleActiveApi } from '$lib/utils/apiHelpers';
  import { formatDate, confirmDelete } from '$lib/utils';
  import { validators, validateFields } from '$lib/utils/validation';
  import type { Page } from '$lib/types/models';

  let pages: Page[] = [];
  let loading = true;
  let drawerOpen = false;
  let drawerMode: 'add' | 'edit' | 'seo' | 'view' = 'add';
  let drawerPage: Page | null = null;

  let formData: Omit<Page, 'id' | 'created' | 'updated' | 'seo'> = {
    name: '',
    slug: '',
    position: 'header',
    content: '',
    active: true
  };

  const positionOptions = ['header', 'footer'];
  let formErrors: Record<string, string> = {};

  onMount(async () => {
    await loadPages();
  });

  async function loadPages() {
    loading = true;
    const result = await loadData<Page[]>('/api/_/pages', 'Failed to load pages');
    if (result) {
      pages = result;
    }
    loading = false;
  }

  function openAdd() {
    formData = {
      name: '',
      slug: '',
      position: 'header',
      content: '',
      active: true
    };
    formErrors = {};
    drawerPage = null;
    drawerMode = 'add';
    drawerOpen = true;
  }

  async function openEdit(page: Page) {
    // Load full page data including content
    const fullPage = await loadData<Page>(`/api/_/pages/${page.id}`, 'Failed to load page');
    if (!fullPage) {
      return;
    }

    formData = {
      name: fullPage.name || '',
      slug: fullPage.slug || '',
      position: fullPage.position || 'header',
      content: fullPage.content ?? '',
      active: fullPage.active !== undefined ? fullPage.active : true
    };
    drawerPage = fullPage;
    formErrors = {};
    drawerMode = 'edit';
    drawerOpen = true;
  }

  function closeDrawer() {
    if (drawerOpen) {
      drawerOpen = false;
      setTimeout(() => {
        drawerPage = null;
        drawerMode = 'add';
      }, 200);
    }
  }

  async function handleSubmit() {
    formErrors = validateFields(formData, [
      { field: 'name', ...validators.minLength(3, 'Name must be at least 3 characters') },
      { field: 'slug', ...validators.minLength(3, 'Slug must be at least 3 characters') }
    ]);

    if (Object.keys(formErrors).length > 0) {
      return;
    }

    const isUpdate = drawerMode === 'edit' && drawerPage !== null;
    const url = isUpdate && drawerPage ? `/api/_/pages/${drawerPage.id}` : '/api/_/pages';
    
    const result = await saveData<Page>(url, formData, isUpdate, 'Page saved', 'Failed to save page');
    if (result) {
      if (isUpdate && drawerPage) {
        // Find and update the specific page in the list reactively
        const pageId = drawerPage.id;
        const pageIndex = pages.findIndex(p => p.id === pageId);
        if (pageIndex !== -1) {
          pages = pages.map((p, i) => 
            i === pageIndex ? { ...result } : p
          );
        }
      } else {
        // For new pages, reload the list
        await loadPages();
      }
      closeDrawer();
    }
  }

  async function handleDelete(page: Page) {
    if (!confirmDelete('page', page.name)) {
      return;
    }

    const success = await deleteData(
      `/api/_/pages/${page.id}`,
      'Page deleted',
      'Failed to delete page'
    );
    if (success) {
      await loadPages();
    }
  }

  async function toggleActive(page: Page, index: number) {
    // Optimistically update UI first
    const newActive = !page.active;
    pages = pages.map((p, i) => 
      i === index ? { ...p, active: newActive } : p
    );
    
    // Then make API call
    const updatedPage = await toggleActiveApi<Page>(
      `/api/_/pages/${page.id}/active`,
      'Page status updated',
      'Failed to update page'
    );
    
    // If API call failed, revert the change
    if (!updatedPage) {
      pages = pages.map((p, i) => 
        i === index ? { ...p, active: page.active } : p
      );
    } else {
      // Update with the response from server including updated timestamp
      pages = pages.map((p, i) => 
        i === index ? { ...updatedPage } : p
      );
    }
  }

  function handleEditorUpdate(event: CustomEvent<string>) {
    formData.content = event.detail;
  }

  function openSeo(page: Page) {
    drawerPage = page;
    drawerMode = 'seo';
    drawerOpen = true;
  }
</script>

<svelte:component this={Main}>
  <div class="flex items-center justify-between mb-5">
    <h1>Pages</h1>
    <FormButton name="Add Page" color="green" ico="plus" on:click={openAdd} />
  </div>

  {#if loading}
    <div class="text-center py-8">Loading...</div>
  {:else if pages.length === 0}
    <div class="text-center py-8 text-gray-500">No pages found</div>
  {:else}
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th class="w-32">Position</th>
          <th class="w-32">Slug</th>
          <th class="w-48">Created</th>
          <th class="w-48">Updated</th>
          <th class="w-24 px-4 py-2"></th>
        </tr>
      </thead>
      <tbody>
        {#each pages as page, index}
          <tr class:opacity-30={!page.active}>
            <td>{page.name}</td>
            <td>{page.position || '-'}</td>
            <td>
              <a href="/{page.slug}" target="_blank">{page.slug}</a>
            </td>
            <td>
              {formatDate(page.created)}
            </td>
            <td>
              {#if page.updated}
                {formatDate(page.updated)}
              {/if}
            </td>
            <td class="px-4 py-2">
              <div class="flex">
                <div class="pr-3">
                  <SvgIcon 
                    name="pencil-square" 
                    className="h-5 w-5 cursor-pointer" 
                    on:click={() => openEdit(page)} 
                    stroke="currentColor"
                  />
                </div>
                <div class="pr-3">
                  <SvgIcon 
                    name="rocket" 
                    className="h-5 w-5 cursor-pointer" 
                    on:click={() => openSeo(page)} 
                    stroke="currentColor"
                  />
                </div>
                <div>
                  <SvgIcon 
                    name={page.active ? 'eye' : 'eye-slash'} 
                    className="h-5 w-5 cursor-pointer" 
                    on:click={() => toggleActive(page, index)} 
                    stroke="currentColor"
                  />
                </div>
              </div>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</svelte:component>

{#if drawerOpen}
  <Drawer isOpen={drawerOpen} on:close={() => closeDrawer()} maxWidth="710px">
    {#if drawerMode === 'seo' && drawerPage}
      <PageSeo page={drawerPage} on:close={closeDrawer} />
    {:else}
      <div class="pb-8">
        <div class="flex items-center">
          <div class="pr-3">
            <h1>{drawerMode === 'add' ? 'New page' : 'Page setup'}</h1>
          </div>
        </div>
      </div>

      <form on:submit|preventDefault={handleSubmit}>
        <div class="flow-root">
          <dl class="-my-3 mx-auto mb-0 mt-4 space-y-4 text-sm">
            <FormInput
              id="name"
              title="name"
              bind:value={formData.name}
              error={formErrors.name}
              ico="at-symbol"
            />
            <div class="flex">
              <div class="pr-3">
                <FormSelect
                  id="position"
                  title="Position"
                  options={positionOptions}
                  bind:value={formData.position}
                  error={formErrors.position}
                />
              </div>
              <div>
                <FormInput
                  id="slug"
                  title="Slug"
                  bind:value={formData.slug}
                  error={formErrors.slug}
                  ico="glob-alt"
                />
              </div>
            </div>

            <hr />
            <p class="font-semibold">Content</p>
            <Editor
              bind:modelValue={formData.content}
              placeholder="type content here"
              on:update:modelValue={handleEditorUpdate}
            />
          </dl>
        </div>

        <div class="pt-8">
          <div class="flex">
            <div class="flex-none">
              <FormButton type="submit" name={drawerMode === 'add' ? 'Add' : 'Save'} color="green" />
              <FormButton type="button" name="Close" color="gray" on:click={closeDrawer} />
            </div>
            <div class="grow"></div>
            {#if drawerMode === 'edit' && drawerPage}
              <div class="mt-4 flex-none">
                <span 
                  role="button" 
                  tabindex="0"
                  on:click={() => drawerPage && handleDelete(drawerPage)} 
                  on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); drawerPage && handleDelete(drawerPage); } }}
                  class="cursor-pointer text-red-700"
                >
                  Delete
                </span>
              </div>
            {/if}
          </div>
        </div>
      </form>
    {/if}
  </Drawer>
{/if}
