// web/admin/src/pages/settings/auth.vue
<template>
  <div class="pb-10">
    <header class="mb-4">
      <h1>Authentication</h1>
    </header>

    <Form @submit="updateAuth" v-slot="{ errors }">
      <FormInput v-model.trim="auth.email" :error="errors.email" rules="required|email" class="w-64" id="email" type="text" title="Email" ico="at-symbol" />
      <div class="pt-5">
        <FormButton type="submit" name="Save" color="green" />
      </div>
    </Form>
    <hr class="mt-5" />

    <div class="mt-5">
      <h2 class="mb-5">JWT parameters</h2>
      <Form @submit="updateJWT" v-slot="{ errors }">
        <div class="mt-5 flex">
          <div class="pr-3">
            <FormInput v-model.trim="jwt.secret" :error="errors.jwt_secret" rules="required|min:30" class="w-64" id="jwt_secret" type="text" title="JWT Secret" ico="key" />
          </div>
          <div>
            <FormInput v-model.trim="jwt.expire_hours" :error="errors.jwt_expire_hours" rules="required|numeric" class="w-64" id="jwt_expire_hours" type="text"
              title="JWT expire hours" ico="key" />
          </div>
        </div>
        <div class="pt-5">
          <FormButton type="submit" name="Save" color="green" />
        </div>
      </Form>
      <hr class="mt-5" />
    </div>

    <div class="mt-5">
      <h2 class="mb-5">Change password</h2>
      <Form @submit="updatePassword" v-slot="{ errors }">
        <FormInput v-model.trim="password.old" :error="errors.password_old" rules="required|min:6" class="w-96" id="password_old" type="password" title="Actual password"
          ico="finger-print" />
        <div class="mt-5 flex">
          <div class="pr-3">
            <FormInput v-model.trim="password.new" :error="errors.password_new" rules="required|min:6" class="w-96" id="password_new" type="password" title="New password"
              ico="finger-print" />
          </div>
          <div>
            <FormInput v-model.trim="password.new2" :error="errors.password_new2" rules="required|confirmed:password_new" class="w-96" id="password_new2" type="password"
              title="Repeat password" ico="finger-print" />
          </div>
        </div>
        <div class="pt-5">
          <FormButton type="submit" name="Save" color="green" />
        </div>
      </Form>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { FormInput, FormButton } from "@/components";
import { showMessage } from "@/utils/message";
import { apiGet, apiUpdate } from "@/utils/api";
import { Form } from "vee-validate";

const auth = ref({});
const jwt = ref({});
const password = ref({});

onMounted(() => {
  apiGet(`/api/_/settings/auth`).then(res => {
    if (res.success) {
      auth.value = res.result;
    }
  });
  apiGet(`/api/_/settings/jwt`).then(res => {
    if (res.success) {
      jwt.value = res.result;
    }
  });
});

const updatePassword = async () => {
  var update = {
    old: password.value.old,
    new: password.value.new,
  };

  await apiUpdate(`/api/_/settings/password`, update).then(res => {
    if (res.success) {
      showMessage(res.message);
    } else {
      showMessage(res.result, "connextError");
    }
  });
};

const updateJWT = async () => {
  jwt.value.expire_hours = Number(jwt.value.expire_hours);
  await apiUpdate(`/api/_/settings/jwt`, jwt.value).then(res => {
    if (res.success) {
      showMessage(res.message);
    } else {
      showMessage(res.result, "connextError");
    }
  });
};

const updateAuth = async () => {
  await apiUpdate(`/api/_/settings/auth`, auth.value).then(res => {
    if (res.success) {
      showMessage(res.message);
    } else {
      showMessage(res.result, "connextError");
    }
  });
};
</script>

// web/admin/src/routes/settings/auth/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Main from '$lib/layouts/Main.svelte';
  import FormButton from '$lib/components/form/Button.svelte';
  import FormInput from '$lib/components/form/Input.svelte';
  import { loadSettings, saveSettings } from '$lib/utils/settingsHelpers';
  import { saveData } from '$lib/utils/apiHelpers';
  import { validators, validateFields } from '$lib/utils/validation';

  interface AuthSettings {
    email: string;
  }

  interface PasswordData {
    old: string;
    new: string;
  }

  let formData: AuthSettings = {
    email: ''
  };
  let passwordData: PasswordData = {
    old: '',
    new: ''
  };
  let formErrors: Record<string, string> = {};
  let passwordErrors: Record<string, string> = {};
  let loading = true;

  onMount(async () => {
    formData = await loadSettings<AuthSettings>('auth', formData);
    loading = false;
  });

  async function handleSubmit() {
    formErrors = validateFields(formData, [
      { field: 'email', ...validators.email('Valid email is required') }
    ]);

    if (Object.keys(formErrors).length > 0) {
      return;
    }

    await saveSettings('auth', formData);
  }

  async function handlePasswordSubmit() {
    passwordErrors = validateFields(passwordData, [
      { field: 'old', ...validators.required('Old password is required') },
      { field: 'new', ...validators.minLength(6, 'New password must be at least 6 characters') }
    ]);

    if (Object.keys(passwordErrors).length > 0) {
      return;
    }

    const result = await saveData<PasswordData>(
      '/api/_/settings/password',
      passwordData,
      true,
      'Password updated',
      'Failed to update password'
    );
    
    if (result !== null) {
      passwordData = { old: '', new: '' };
    }
  }
</script>

<svelte:component this={Main}>
  <h1 class="mb-5">Authentication Settings</h1>

  {#if loading}
    <div class="text-center py-8">Loading...</div>
  {:else}
    <form on:submit|preventDefault={handleSubmit} class="space-y-4 max-w-2xl">
      <h2 class="text-xl font-bold mb-4">Email</h2>
      <FormInput
        id="email"
        type="email"
        title="Email"
        bind:value={formData.email}
        error={formErrors.email}
        ico="at-symbol"
      />
      <div class="pt-4">
        <FormButton type="submit" name="Save" color="green" />
      </div>
    </form>

    <hr class="mt-5" />

    <form on:submit|preventDefault={handlePasswordSubmit} class="space-y-4 max-w-2xl">
      <h2 class="text-xl font-bold mb-4">Change Password</h2>
      <FormInput
        id="old_password"
        type="password"
        title="Old Password"
        bind:value={passwordData.old}
        error={passwordErrors.old}
        ico="finger-print"
      />
      <FormInput
        id="new_password"
        type="password"
        title="New Password"
        bind:value={passwordData.new}
        error={passwordErrors.new}
        ico="finger-print"
      />
      <div class="pt-4">
        <FormButton type="submit" name="Update Password" color="green" />
      </div>
    </form>
  {/if}
</svelte:component>
