// web/admin/src/lib/components/page/Seo.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { createEventDispatcher } from 'svelte'
  import FormButton from '../form/Button.svelte'
  import FormInput from '../form/Input.svelte'
  import FormTextarea from '../form/Textarea.svelte'
  import { loadData, saveData } from '$lib/utils/apiHelpers'
  import type { Page } from '$lib/types/models'

  export let page: Page

  const dispatch = createEventDispatcher()

  let seoData = {
    title: '',
    keywords: '',
    description: ''
  }

  // Reactively load data when page.id changes
  $: if (page?.id) {
    loadPage()
  }

  async function loadPage() {
    if (!page?.id) return

    const pageData = await loadData<Page>(`/api/_/pages/${page.id}`, 'Failed to load page')
    if (pageData) {
      seoData = {
        title: pageData.seo?.title || '',
        keywords: pageData.seo?.keywords || '',
        description: pageData.seo?.description || ''
      }
    }
  }

  async function handleSubmit() {
    await saveData<Page>(
      `/api/_/pages/${page.id}`,
      { seo: seoData },
      true,
      'SEO settings saved',
      'Failed to save SEO settings'
    )
  }

  function close() {
    dispatch('close')
  }
</script>

<div>
  <div class="pb-8">
    <div class="flex items-center">
      <div class="pr-3">
        <h1>SEO</h1>
      </div>
    </div>
  </div>

  <form on:submit|preventDefault={handleSubmit}>
    <div class="flow-root">
      <dl class="mx-auto -my-3 mt-2 mb-0 space-y-4 text-sm">
        <FormInput id="seo-title" title="Title" bind:value={seoData.title} ico="glob-alt" />
        <FormInput id="seo-keywords" title="Keywords" bind:value={seoData.keywords} ico="glob-alt" />
        <hr />
        <FormTextarea id="seo-description" title="Description" bind:value={seoData.description} />
      </dl>
    </div>

    <div class="pt-8">
      <div class="flex">
        <div class="flex-none">
          <FormButton type="submit" name="Save" color="green" />
          <FormButton type="button" name="Close" color="gray" on:click={close} />
        </div>
        <div class="grow"></div>
      </div>
    </div>
  </form>
</div>

// web/admin/src/components/page/Seo.vue
<template>
  <div>
    <div class="pb-8">
      <div class="flex items-center">
        <div class="pr-3">
          <h1>SEO</h1>
        </div>
      </div>
    </div>

    <Form @submit="updateSeo" v-slot="{ errors }">
      <div class="flow-root">
        <dl class="-my-3 mx-auto mb-0 mt-2 space-y-4 text-sm">
          <FormInput v-model="page.seo.title" :error="errors.name" id="title" type="text" title="Title" ico="glob-alt" />
          <FormInput v-model="page.seo.keywords" :error="errors.slug" id="keywords" type="text" title="Keywords" ico="glob-alt" />
          <hr />
          <FormTextarea v-model="page.seo.description" id="textarea" name="Description" />
        </dl>
      </div>
      <div class="pt-8">
        <div class="flex">
          <div class="flex-none">
            <FormButton type="submit" name="Save" color="green" class="mr-3" />
            <FormButton type="submit" name="Close" color="gray" @click="close" />
          </div>
          <div class="grow"></div>
        </div>
      </div>
    </Form>
  </div>
</template>

<script setup>
import { computed } from "vue";

import FormInput from "@/components/form/Input.vue";
import FormButton from "@/components/form/Button.vue";
import FormTextarea from "@/components/form/Textarea.vue";
import { showMessage } from "@/utils/message";
import { apiUpdate } from "@/utils/api";

import { Form } from "vee-validate";

const props = defineProps({
  page: {
    required: true,
  },
  updateActive: Function,
  close: Function,
});

const page = computed({
  get: () => {
    return props.page;
  },
  set: (val) => {
    emits("update:modelValue", val);
  },
});

const updateSeo = async () => {
  const update = { ...page.value };
  apiUpdate(`/api/_/pages/${update.id}`, update).then(res => {
    if (res.success) {
      showMessage(res.message);
    } else {
      showMessage(res.result, "connextError");
    }
  });
};
</script>
